/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef VMIDMT_HAL_HWIO_H
#define VMIDMT_HAL_HWIO_H

#include <lib/mmio.h>

#define in_dword(addr) mmio_read_32((addr))
#define in_dword_masked(addr, mask) (mmio_read_32((addr)) & (uint32_t)(mask))
#define out_dword_masked_ns(io, mask, val, current_reg_content)                \
	mmio_write_32((io),                                                    \
		      (((uint32_t)(current_reg_content) & ~(uint32_t)(mask)) | \
		       ((uint32_t)(val) & (uint32_t)(mask))))

#define VMIDMT_SCR0_ADDR(b) (b)
#define VMIDMT_SCR0_PHYS(b) (b)
#define VMIDMT_SCR0_RMSK 0xffffffff
#define VMIDMT_SCR0_SHFT 0
#define VMIDMT_SCR0_IN(b) in_dword_masked(VMIDMT_SCR0_ADDR(b), VMIDMT_SCR0_RMSK)
#define VMIDMT_SCR0_INM(b, m) in_dword_masked(VMIDMT_SCR0_ADDR(b), (m))
#define VMIDMT_SCR0_OUT(b, v) mmio_write_32(VMIDMT_SCR0_ADDR(b), (v))
#define VMIDMT_SCR0_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_SCR0_ADDR(b), (m), (v), VMIDMT_SCR0_IN(b))

#define VMIDMT_SCR0_NSCFG_BMSK 0x30000000
#define VMIDMT_SCR0_NSCFG_SHFT 0x1c
#define VMIDMT_SCR0_WACFG_BMSK 0x0c000000
#define VMIDMT_SCR0_WACFG_SHFT 0x1a
#define VMIDMT_SCR0_RACFG_BMSK 0x03000000
#define VMIDMT_SCR0_RACFG_SHFT 0x18
#define VMIDMT_SCR0_SHCFG_BMSK 0x00C00000
#define VMIDMT_SCR0_SHCFG_SHFT 0x16
#define VMIDMT_SCR0_SMCFCFG_BMSK 0x00200000
#define VMIDMT_SCR0_SMCFCFG_SHFT 0x15
#define VMIDMT_SCR0_MTCFG_BMSK 0x00100000
#define VMIDMT_SCR0_MTCFG_SHFT 0x14
#define VMIDMT_SCR0_MEMATTR_BMSK 0x000F0000
#define VMIDMT_SCR0_MEMATTR_SHFT 0x10
#define VMIDMT_SCR0_VMIDPNE_BMSK 0x00000800
#define VMIDMT_SCR0_VMIDPNE_SHFT 0x0b
#define VMIDMT_SCR0_USFCFG_BMSK 0x00000400
#define VMIDMT_SCR0_USFCFG_SHFT 0x0a
#define VMIDMT_SCR0_TRANSIENTCFG_BMSK 0x000000C0
#define VMIDMT_SCR0_TRANSIENTCFG_SHFT 0x06
#define VMIDMT_SCR0_GCFGFIE_BMSK 0x00000020
#define VMIDMT_SCR0_GCFGFIE_SHFT 0x05
#define VMIDMT_SCR0_GCFGFRE_BMSK 0x00000010
#define VMIDMT_SCR0_GCFGFRE_SHFT 0x04
#define VMIDMT_SCR0_GFIE_BMSK 0x00000004
#define VMIDMT_SCR0_GFIE_SHFT 0x02
#define VMIDMT_SCR0_CLIENTPD_BMSK 0x00000001
#define VMIDMT_SCR0_CLIENTPD_SHFT 0x00

#define VMIDMT_CR0_ADDR(b) (b)
#define VMIDMT_CR0_PHYS(b) (b)
#define VMIDMT_CR0_RMSK 0x0fffffff
#define VMIDMT_CR0_SHFT 0
#define VMIDMT_CR0_IN(b) in_dword_masked(VMIDMT_CR0_ADDR(b), VMIDMT_CR0_RMSK)
#define VMIDMT_CR0_INM(b, m) in_dword_masked(VMIDMT_CR0_ADDR(b), (m))
#define VMIDMT_CR0_OUT(b, v) mmio_write_32(VMIDMT_CR0_ADDR(b), (v))
#define VMIDMT_CR0_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_CR0_ADDR(b), (m), (v), VMIDMT_CR0_IN(b))

#define VMIDMT_CR0_WACFG_BMSK 0x0c000000
#define VMIDMT_CR0_WACFG_SHFT 0x1a
#define VMIDMT_CR0_RACFG_BMSK 0x03000000
#define VMIDMT_CR0_RACFG_SHFT 0x18
#define VMIDMT_CR0_SHCFG_BMSK 0x00C00000
#define VMIDMT_CR0_SHCFG_SHFT 0x16
#define VMIDMT_CR0_SMCFCFG_BMSK 0x00200000
#define VMIDMT_CR0_SMCFCFG_SHFT 0x15
#define VMIDMT_CR0_MTCFG_BMSK 0x00100000
#define VMIDMT_CR0_MTCFG_SHFT 0x14
#define VMIDMT_CR0_MEMATTR_BMSK 0x000F0000
#define VMIDMT_CR0_MEMATTR_SHFT 0x10
#define VMIDMT_CR0_VMIDPNE_BMSK 0x00000800
#define VMIDMT_CR0_VMIDPNE_SHFT 0x0b
#define VMIDMT_CR0_USFCFG_BMSK 0x00000400
#define VMIDMT_CR0_USFCFG_SHFT 0x0a
#define VMIDMT_CR0_TRANSIENTCFG_BMSK 0x000000C0
#define VMIDMT_CR0_TRANSIENTCFG_SHFT 0x06
#define VMIDMT_CR0_GCFGFIE_BMSK 0x00000020
#define VMIDMT_CR0_GCFGFIE_SHFT 0x05
#define VMIDMT_CR0_GCFGFRE_BMSK 0x00000010
#define VMIDMT_CR0_GCFGFRE_SHFT 0x04
#define VMIDMT_CR0_GFIE_BMSK 0x00000004
#define VMIDMT_CR0_GFIE_SHFT 0x02
#define VMIDMT_CR0_CLIENTPD_BMSK 0x00000001
#define VMIDMT_CR0_CLIENTPD_SHFT 0x00

#define VMIDMT_NSCR0_ADDR(b) (b + 0x00000400)
#define VMIDMT_NSCR0_PHYS(b) (b + 0x00000400)
#define VMIDMT_NSCR0_RMSK 0x0fffffff
#define VMIDMT_NSCR0_SHFT 0
#define VMIDMT_NSCR0_IN(b) \
	in_dword_masked(VMIDMT_NSCR0_ADDR(b), VMIDMT_NSCR0_RMSK)
#define VMIDMT_NSCR0_INM(b, m) in_dword_masked(VMIDMT_NSCR0_ADDR(b), (m))
#define VMIDMT_NSCR0_OUT(b, v) mmio_write_32(VMIDMT_NSCR0_ADDR(b), (v))
#define VMIDMT_NSCR0_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_NSCR0_ADDR(b), (m), (v), VMIDMT_NSCR0_IN(b))

#define VMIDMT_NSCR0_WACFG_BMSK 0x0c000000
#define VMIDMT_NSCR0_WACFG_SHFT 0x1a
#define VMIDMT_NSCR0_RACFG_BMSK 0x03000000
#define VMIDMT_NSCR0_RACFG_SHFT 0x18
#define VMIDMT_NSCR0_SHCFG_BMSK 0x00C00000
#define VMIDMT_NSCR0_SHCFG_SHFT 0x16
#define VMIDMT_NSCR0_SMCFCFG_BMSK 0x00200000
#define VMIDMT_NSCR0_SMCFCFG_SHFT 0x15
#define VMIDMT_NSCR0_MTCFG_BMSK 0x00100000
#define VMIDMT_NSCR0_MTCFG_SHFT 0x14
#define VMIDMT_NSCR0_MEMATTR_BMSK 0x000F0000
#define VMIDMT_NSCR0_MEMATTR_SHFT 0x10
#define VMIDMT_NSCR0_VMIDPNE_BMSK 0x00000800
#define VMIDMT_NSCR0_VMIDPNE_SHFT 0x0b
#define VMIDMT_NSCR0_USFCFG_BMSK 0x00000400
#define VMIDMT_NSCR0_USFCFG_SHFT 0x0a
#define VMIDMT_NSCR0_TRANSIENTCFG_BMSK 0x000000C0
#define VMIDMT_NSCR0_TRANSIENTCFG_SHFT 0x06
#define VMIDMT_NSCR0_GCFGFIE_BMSK 0x00000020
#define VMIDMT_NSCR0_GCFGFIE_SHFT 0x05
#define VMIDMT_NSCR0_GCFGFRE_BMSK 0x00000010
#define VMIDMT_NSCR0_GCFGFRE_SHFT 0x04
#define VMIDMT_NSCR0_GFIE_BMSK 0x00000004
#define VMIDMT_NSCR0_GFIE_SHFT 0x02
#define VMIDMT_NSCR0_CLIENTPD_BMSK 0x00000001
#define VMIDMT_NSCR0_CLIENTPD_SHFT 0x00

#define VMIDMT_SCR1_ADDR(b) (b + 0x00000004)
#define VMIDMT_SCR1_PHYS(b) (b + 0x00000004)
#define VMIDMT_SCR1_RMSK 0x0100FF00
#define VMIDMT_SCR1_SHFT 0
#define VMIDMT_SCR1_IN(b) in_dword_masked(VMIDMT_SCR1_ADDR(b), VMIDMT_SCR1_RMSK)
#define VMIDMT_SCR1_INM(b, m) in_dword_masked(VMIDMT_SCR1_ADDR(b), (m))
#define VMIDMT_SCR1_OUT(b, v) mmio_write_32(VMIDMT_SCR1_ADDR(b), (v))
#define VMIDMT_SCR1_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_SCR1_ADDR(b), (m), (v), VMIDMT_SCR1_IN(b))

#define VMIDMT_SCR1_GASRAE_BMSK 0x01000000
#define VMIDMT_SCR1_GASRAE_SHFT 0x18
#define VMIDMT_SCR1_NSNUMSMRGO_BMSK 0x0000ff00
#define VMIDMT_SCR1_NSNUMSMRGO_SHFT 0x08

#define VMIDMT_SCR2_ADDR(b) (b + 0x00000008)
#define VMIDMT_SCR2_PHYS(b) (b + 0x00000008)
#define VMIDMT_SCR2_RMSK 0x0000FF00
#define VMIDMT_SCR2_SHFT 0
#define VMIDMT_SCR2_IN(b) in_dword_masked(VMIDMT_SCR2_ADDR(b), VMIDMT_SCR2_RMSK)
#define VMIDMT_SCR2_INM(b, m) in_dword_masked(VMIDMT_SCR2_ADDR(b), (m))
#define VMIDMT_SCR2_OUT(b, v) mmio_write_32(VMIDMT_SCR2_ADDR(b), (v))
#define VMIDMT_SCR2_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_SCR2_ADDR(b), (m), (v), VMIDMT_SCR2_IN(b))

#define VMIDMT_SCR2_BPVMID_BMSK 0x000000ff
#define VMIDMT_SCR2_BPVMID_SHFT 0x00

#define VMIDMT_CR2_ADDR(b) (b + 0x00000008)
#define VMIDMT_CR2_PHYS(b) (b + 0x00000008)
#define VMIDMT_CR2_RMSK 0x0000FF00
#define VMIDMT_CR2_SHFT 0
#define VMIDMT_CR2_IN(b) in_dword_masked(VMIDMT_CR2_ADDR(b), VMIDMT_CR2_RMSK)
#define VMIDMT_CR2_INM(b, m) in_dword_masked(VMIDMT_CR2_ADDR(b), (m))
#define VMIDMT_CR2_OUT(b, v) mmio_write_32(VMIDMT_CR2_ADDR(b), (v))
#define VMIDMT_CR2_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_CR2_ADDR(b), (m), (v), VMIDMT_CR2_IN(b))

#define VMIDMT_CR2_BPVMID_BMSK 0x000000ff
#define VMIDMT_CR2_BPVMID_SHFT 0x00

#define VMIDMT_NSCR2_ADDR(b) (b + 0x00000408)
#define VMIDMT_NSCR2_PHYS(b) (b + 0x00000408)
#define VMIDMT_NSCR2_RMSK 0x0000FF00
#define VMIDMT_NSCR2_SHFT 0
#define VMIDMT_NSCR2_IN(b) \
	in_dword_masked(VMIDMT_NSCR2_ADDR(b), VMIDMT_NSCR2_RMSK)
#define VMIDMT_NSCR2_INM(b, m) in_dword_masked(VMIDMT_NSCR2_ADDR(b), (m))
#define VMIDMT_NSCR2_OUT(b, v) mmio_write_32(VMIDMT_NSCR2_ADDR(b), (v))
#define VMIDMT_NSCR2_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_NSCR2_ADDR(b), (m), (v), VMIDMT_NSCR2_IN(b))

#define VMIDMT_NSCR2_BPVMID_BMSK 0x000000ff
#define VMIDMT_NSCR2_BPVMID_SHFT 0x00

#define VMIDMT_SACR_ADDR(b) (b + 0x00000010)
#define VMIDMT_SACR_PHYS(b) (b + 0x00000010)
#define VMIDMT_SACR_RMSK 0x70000013
#define VMIDMT_SACR_SHFT 0
#define VMIDMT_SACR_IN(b) in_dword_masked(VMIDMT_SACR_ADDR(b), VMIDMT_SACR_RMSK)
#define VMIDMT_SACR_INM(b, m) in_dword_masked(VMIDMT_SACR_ADDR(b), (m))
#define VMIDMT_SACR_OUT(b, v) mmio_write_32(VMIDMT_SACR_ADDR(b), (v))
#define VMIDMT_SACR_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_SACR_ADDR(b), (m), (v), VMIDMT_SACR_IN(b))

#define VMIDMT_SACR_BPRCNSH_BMSK 0x40000000
#define VMIDMT_SACR_BPRCNSH_SHFT 0x1e
#define VMIDMT_SACR_BPRCISH_BMSK 0x02000000
#define VMIDMT_SACR_BPRCISH_SHFT 0x1d
#define VMIDMT_SACR_BPRCOSH_BMSK 0x01000000
#define VMIDMT_SACR_BPRCOSH_SHFT 0x1c
#define VMIDMT_SACR_REQPRIORITYCFG_BMSK 0x00000010
#define VMIDMT_SACR_REQPRIORITYCFG_SHFT 0x04
#define VMIDMT_SACR_REQPRIORITY_BMSK 0x00000003
#define VMIDMT_SACR_REQPRIORITY_SHFT 0x00

#define VMIDMT_ACR_ADDR(b) (b + 0x00000010)
#define VMIDMT_ACR_PHYS(b) (b + 0x00000010)
#define VMIDMT_ACR_RMSK 0x70000013
#define VMIDMT_ACR_SHFT 0
#define VMIDMT_ACR_IN(b) in_dword_masked(VMIDMT_ACR_ADDR(b), VMIDMT_ACR_RMSK)
#define VMIDMT_ACR_INM(b, m) in_dword_masked(VMIDMT_ACR_ADDR(b), (m))
#define VMIDMT_ACR_OUT(b, v) mmio_write_32(VMIDMT_ACR_ADDR(b), (v))
#define VMIDMT_ACR_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_ACR_ADDR(b), (m), (v), VMIDMT_ACR_IN(b))

#define VMIDMT_ACR_BPRCNSH_BMSK 0x40000000
#define VMIDMT_ACR_BPRCNSH_SHFT 0x1e
#define VMIDMT_ACR_BPRCISH_BMSK 0x02000000
#define VMIDMT_ACR_BPRCISH_SHFT 0x1d
#define VMIDMT_ACR_BPRCOSH_BMSK 0x01000000
#define VMIDMT_ACR_BPRCOSH_SHFT 0x1c
#define VMIDMT_ACR_REQPRIORITYCFG_BMSK 0x00000010
#define VMIDMT_ACR_REQPRIORITYCFG_SHFT 0x04
#define VMIDMT_ACR_REQPRIORITY_BMSK 0x00000003
#define VMIDMT_ACR_REQPRIORITY_SHFT 0x00

#define VMIDMT_NSACR_ADDR(b) (b + 0x00000410)
#define VMIDMT_NSACR_PHYS(b) (b + 0x00000410)
#define VMIDMT_NSACR_RMSK 0x70000013
#define VMIDMT_NSACR_SHFT 0
#define VMIDMT_NSACR_IN(b) \
	in_dword_masked(VMIDMT_NSACR_ADDR(b), VMIDMT_NSACR_RMSK)
#define VMIDMT_NSACR_INM(b, m) in_dword_masked(VMIDMT_NSACR_ADDR(b), (m))
#define VMIDMT_NSACR_OUT(b, v) mmio_write_32(VMIDMT_NSACR_ADDR(b), (v))
#define VMIDMT_NSACR_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_NSACR_ADDR(b), (m), (v), VMIDMT_NSACR_IN(b))

#define VMIDMT_NSACR_BPRCNSH_BMSK 0x40000000
#define VMIDMT_NSACR_BPRCNSH_SHFT 0x1e
#define VMIDMT_NSACR_BPRCISH_BMSK 0x02000000
#define VMIDMT_NSACR_BPRCISH_SHFT 0x1d
#define VMIDMT_NSACR_BPRCOSH_BMSK 0x01000000
#define VMIDMT_NSACR_BPRCOSH_SHFT 0x1c
#define VMIDMT_NSACR_REQPRIORITYCFG_BMSK 0x00000010
#define VMIDMT_NSACR_REQPRIORITYCFG_SHFT 0x04
#define VMIDMT_NSACR_REQPRIORITY_BMSK 0x00000003
#define VMIDMT_NSACR_REQPRIORITY_SHFT 0x00

#define VMIDMT_IDR0_ADDR(b) (b + 0x00000020)
#define VMIDMT_IDR0_PHYS(b) (b + 0x00000020)
#define VMIDMT_IDR0_RMSK 0x88001EFF
#define VMIDMT_IDR0_SHFT 0
#define VMIDMT_IDR0_IN(b) in_dword_masked(VMIDMT_IDR0_ADDR(b), VMIDMT_IDR0_RMSK)
#define VMIDMT_IDR0_INM(b, m) in_dword_masked(VMIDMT_IDR0_ADDR(b), (m))

#define VMIDMT_IDR0_SES_BMSK 0x80000000
#define VMIDMT_IDR0_SES_SHFT 0x1f
#define VMIDMT_IDR0_SMS_BMSK 0x08000000
#define VMIDMT_IDR0_SMS_SHFT 0x1b
#define VMIDMT_IDR0_NUMSIDB_BMSK 0x00001e00
#define VMIDMT_IDR0_NUMSIDB_SHFT 0x09
#define VMIDMT_IDR0_NUMSMRG_BMSK 0x000000ff
#define VMIDMT_IDR0_NUMSMRG_SHFT 0x00

#define VMIDMT_IDR1_ADDR(b) (b + 0x00000024)
#define VMIDMT_IDR1_PHYS(b) (b + 0x00000024)
#define VMIDMT_IDR1_RMSK 0x00009f00
#define VMIDMT_IDR1_SHFT 0
#define VMIDMT_IDR1_IN(b) in_dword_masked(VMIDMT_IDR1_ADDR(b), VMIDMT_IDR1_RMSK)
#define VMIDMT_IDR1_INM(b, m) in_dword_masked(VMIDMT_IDR1_ADDR(b), (m))

#define VMIDMT_IDR1_SMCD_BMSK 0x00008000
#define VMIDMT_IDR1_SMCD_SHFT 0x0f
#define VMIDMT_IDR1_SSDTP_BMSK 0x00001000
#define VMIDMT_IDR1_SSDTP_SHFT 0x0c
#define VMIDMT_IDR1_NUMSSDNDXB_BMSK 0x00000f00
#define VMIDMT_IDR1_NUMSSDNDXB_SHFT 0x08

#define VMIDMT_IDR2_ADDR(b) (b + 0x00000028)
#define VMIDMT_IDR2_PHYS(b) (b + 0x00000028)
#define VMIDMT_IDR2_RMSK 0x000000ff
#define VMIDMT_IDR2_SHFT 0
#define VMIDMT_IDR2_IN(b) in_dword_masked(VMIDMT_IDR2_ADDR(b), VMIDMT_IDR2_RMSK)
#define VMIDMT_IDR2_INM(b, m) in_dword_masked(VMIDMT_IDR2_ADDR(b), (m))

#define VMIDMT_IDR2_OAS_BMSK 0x000000f0
#define VMIDMT_IDR2_OAS_SHFT 0x04
#define VMIDMT_IDR2_IAS_BMSK 0x0000000f
#define VMIDMT_IDR2_IAS_SHFT 0x00

#define VMIDMT_IDR4_ADDR(b) (b + 0x00000030)
#define VMIDMT_IDR4_PHYS(b) (b + 0x00000030)
#define VMIDMT_IDR4_RMSK 0xffffffff
#define VMIDMT_IDR4_SHFT 0
#define VMIDMT_IDR4_IN(b) in_dword_masked(VMIDMT_IDR4_ADDR(b), VMIDMT_IDR4_RMSK)
#define VMIDMT_IDR4_INM(b, m) in_dword_masked(VMIDMT_IDR4_ADDR(b), (m))

#define VMIDMT_IDR4_MAJOR_BMSK 0xf0000000
#define VMIDMT_IDR4_MAJOR_SHFT 0x1c
#define VMIDMT_IDR4_MINOR_BMSK 0x000f0000
#define VMIDMT_IDR4_MINOR_SHFT 0x10
#define VMIDMT_IDR4_STEP_BMSK 0x0000ffff
#define VMIDMT_IDR4_STEP_SHFT 0x00

#define VMIDMT_IDR5_ADDR(b) (b + 0x00000034)
#define VMIDMT_IDR5_PHYS(b) (b + 0x00000034)
#define VMIDMT_IDR5_RMSK 0xffffffff
#define VMIDMT_IDR5_SHFT 0
#define VMIDMT_IDR5_IN(b) in_dword_masked(VMIDMT_IDR5_ADDR(b), VMIDMT_IDR5_RMSK)
#define VMIDMT_IDR5_INM(b, m) in_dword_masked(VMIDMT_IDR5_ADDR(b), (m))

#define VMIDMT_IDR5_NUMMSDRB_BMSK 0x00ff0000
#define VMIDMT_IDR5_NUMMSDRB_SHFT 0x10
#define VMIDMT_IDR5_MSAE_BMSK 0x00000200
#define VMIDMT_IDR5_MSAE_SHFT 0x09
#define VMIDMT_IDR5_QRIBE_BMSK 0x00000100
#define VMIDMT_IDR5_QRIBE_SHFT 0x08
#define VMIDMT_IDR5_NVMID_BMSK 0x000000ff
#define VMIDMT_IDR5_NVMID_SHFT 0x00

#define VMIDMT_IDR7_ADDR(b) (b + 0x0000003c)
#define VMIDMT_IDR7_PHYS(b) (b + 0x0000003c)
#define VMIDMT_IDR7_RMSK 0x000000ff
#define VMIDMT_IDR7_SHFT 0
#define VMIDMT_IDR7_IN(b) in_dword_masked(VMIDMT_IDR7_ADDR(b), VMIDMT_IDR7_RMSK)
#define VMIDMT_IDR7_INM(b, m) in_dword_masked(VMIDMT_IDR7_ADDR(b), (m))

#define VMIDMT_IDR7_MAJOR_BMSK 0x000000f0
#define VMIDMT_IDR7_MAJOR_SHFT 0x04
#define VMIDMT_IDR7_MINOR_BMSK 0x0000000f
#define VMIDMT_IDR7_MINOR_SHFT 0x00

#define VMIDMT_SGFAR0_ADDR(b) (b + 0x00000040)
#define VMIDMT_SGFAR0_PHYS(b) (b + 0x00000040)
#define VMIDMT_SGFAR0_RMSK 0xffffffff
#define VMIDMT_SGFAR0_SHFT 0
#define VMIDMT_SGFAR0_IN(b) \
	in_dword_masked(VMIDMT_SGFAR0_ADDR(b), VMIDMT_SGFAR0_RMSK)
#define VMIDMT_SGFAR0_INM(b, m) in_dword_masked(VMIDMT_SGFAR0_ADDR(b), (m))
#define VMIDMT_SGFAR0_OUT(b, v) mmio_write_32(VMIDMT_SGFAR0_ADDR(b), (v))
#define VMIDMT_SGFAR0_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_SGFAR0_ADDR(b), (m), (v), \
			    VMIDMT_SGFAR0_IN(b))

#define VMIDMT_SGFAR0_ADDR_BMSK 0xffffffff
#define VMIDMT_SGFAR0_ADDR_SHFT 0x00

#define VMIDMT_SGFAR1_ADDR(b) (b + 0x00000044)
#define VMIDMT_SGFAR1_PHYS(b) (b + 0x00000044)
#define VMIDMT_SGFAR1_RMSK 0xffffffff
#define VMIDMT_SGFAR1_SHFT 0
#define VMIDMT_SGFAR1_IN(b) \
	in_dword_masked(VMIDMT_SGFAR1_ADDR(b), VMIDMT_SGFAR1_RMSK)
#define VMIDMT_SGFAR1_INM(b, m) in_dword_masked(VMIDMT_SGFAR1_ADDR(b), (m))
#define VMIDMT_SGFAR1_OUT(b, v) mmio_write_32(VMIDMT_SGFAR1_ADDR(b), (v))
#define VMIDMT_SGFAR1_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_SGFAR1_ADDR(b), (m), (v), \
			    VMIDMT_SGFAR1_IN(b))

#define VMIDMT_SGFAR1_ADDR_BMSK 0xffffffff
#define VMIDMT_SGFAR1_ADDR_SHFT 0x00

#define VMIDMT_GFAR0_ADDR(b) (b + 0x00000040)
#define VMIDMT_GFAR0_PHYS(b) (b + 0x00000040)
#define VMIDMT_GFAR0_RMSK 0xffffffff
#define VMIDMT_GFAR0_SHFT 0
#define VMIDMT_GFAR0_IN(b) \
	in_dword_masked(VMIDMT_GFAR0_ADDR(b), VMIDMT_GFAR0_RMSK)
#define VMIDMT_GFAR0_INM(b, m) in_dword_masked(VMIDMT_GFAR0_ADDR(b), (m))
#define VMIDMT_GFAR0_OUT(b, v) mmio_write_32(VMIDMT_GFAR0_ADDR(b), (v))
#define VMIDMT_GFAR0_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_GFAR0_ADDR(b), (m), (v), VMIDMT_GFAR0_IN(b))

#define VMIDMT_GFAR0_ADDR_BMSK 0xffffffff
#define VMIDMT_GFAR0_ADDR_SHFT 0x00

#define VMIDMT_GFAR1_ADDR(b) (b + 0x00000044)
#define VMIDMT_GFAR1_PHYS(b) (b + 0x00000044)
#define VMIDMT_GFAR1_RMSK 0xffffffff
#define VMIDMT_GFAR1_SHFT 0
#define VMIDMT_GFAR1_IN(b) \
	in_dword_masked(VMIDMT_GFAR1_ADDR(b), VMIDMT_GFAR1_RMSK)
#define VMIDMT_GFAR1_INM(b, m) in_dword_masked(VMIDMT_GFAR1_ADDR(b), (m))
#define VMIDMT_GFAR1_OUT(b, v) mmio_write_32(VMIDMT_GFAR1_ADDR(b), (v))
#define VMIDMT_GFAR1_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_GFAR1_ADDR(b), (m), (v), VMIDMT_GFAR1_IN(b))

#define VMIDMT_GFAR1_ADDR_BMSK 0xffffffff
#define VMIDMT_GFAR1_ADDR_SHFT 0x00

#define VMIDMT_NSGFAR0_ADDR(b) (b + 0x00000440)
#define VMIDMT_NSGFAR0_PHYS(b) (b + 0x00000440)
#define VMIDMT_NSGFAR0_RMSK 0xffffffff
#define VMIDMT_NSGFAR0_SHFT 0
#define VMIDMT_NSGFAR0_IN(b) \
	in_dword_masked(VMIDMT_NSGFAR0_ADDR(b), VMIDMT_NSGFAR0_RMSK)
#define VMIDMT_NSGFAR0_INM(b, m) in_dword_masked(VMIDMT_NSGFAR0_ADDR(b), (m))
#define VMIDMT_NSGFAR0_OUT(b, v) mmio_write_32(VMIDMT_NSGFAR0_ADDR(b), (v))
#define VMIDMT_NSGFAR0_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_NSGFAR0_ADDR(b), (m), (v), \
			    VMIDMT_NSGFAR0_IN(b))

#define VMIDMT_NSGFAR0_ADDR_BMSK 0xffffffff
#define VMIDMT_NSGFAR0_ADDR_SHFT 0x00

#define VMIDMT_NSGFAR1_ADDR(b) (b + 0x00000444)
#define VMIDMT_NSGFAR1_PHYS(b) (b + 0x00000444)
#define VMIDMT_NSGFAR1_RMSK 0xffffffff
#define VMIDMT_NSGFAR1_SHFT 0
#define VMIDMT_NSGFAR1_IN(b) \
	in_dword_masked(VMIDMT_NSGFAR1_ADDR(b), VMIDMT_NSGFAR1_RMSK)
#define VMIDMT_NSGFAR1_INM(b, m) in_dword_masked(VMIDMT_NSGFAR1_ADDR(b), (m))
#define VMIDMT_NSGFAR1_OUT(b, v) mmio_write_32(VMIDMT_NSGFAR1_ADDR(b), (v))
#define VMIDMT_NSGFAR1_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_NSGFAR1_ADDR(b), (m), (v), \
			    VMIDMT_NSGFAR1_IN(b))

#define VMIDMT_NSGFAR1_ADDR_BMSK 0xffffffff
#define VMIDMT_NSGFAR1_ADDR_SHFT 0x00

#define VMIDMT_SGFSR_ADDR(b) (b + 0x00000048)
#define VMIDMT_SGFSR_PHYS(b) (b + 0x00000048)
#define VMIDMT_SGFSR_RMSK 0xc00000a6
#define VMIDMT_SGFSR_SHFT 0
#define VMIDMT_SGFSR_IN(b) \
	in_dword_masked(VMIDMT_SGFSR_ADDR(b), VMIDMT_SGFSR_RMSK)
#define VMIDMT_SGFSR_INM(b, m) in_dword_masked(VMIDMT_SGFSR_ADDR(b), (m))
#define VMIDMT_SGFSR_OUT(b, v) mmio_write_32(VMIDMT_SGFSR_ADDR(b), (v))
#define VMIDMT_SGFSR_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_SGFSR_ADDR(b), (m), (v), VMIDMT_SGFSR_IN(b))

#define VMIDMT_SGFSR_CLMULTI_BMSK 0x80000000
#define VMIDMT_SGFSR_CLMULTI_SHFT 0x1f
#define VMIDMT_SGFSR_CFGMULTI_BMSK 0x40000000
#define VMIDMT_SGFSR_CFGMULTI_SHFT 0x1e
#define VMIDMT_SGFSR_PF_BMSK 0x00000080
#define VMIDMT_SGFSR_PF_SHFT 0x07
#define VMIDMT_SGFSR_CAF_BMSK 0x00000020
#define VMIDMT_SGFSR_CAF_SHFT 0x05
#define VMIDMT_SGFSR_SMCF_BMSK 0x00000004
#define VMIDMT_SGFSR_SMCF_SHFT 0x02
#define VMIDMT_SGFSR_USF_BMSK 0x00000002
#define VMIDMT_SGFSR_USF_SHFT 0x01

#define VMIDMT_GFSR_ADDR(b) (b + 0x00000048)
#define VMIDMT_GFSR_PHYS(b) (b + 0x00000048)
#define VMIDMT_GFSR_RMSK 0xc00000a6
#define VMIDMT_GFSR_SHFT 0
#define VMIDMT_GFSR_IN(b) in_dword_masked(VMIDMT_GFSR_ADDR(b), VMIDMT_GFSR_RMSK)
#define VMIDMT_GFSR_INM(b, m) in_dword_masked(VMIDMT_GFSR_ADDR(b), (m))
#define VMIDMT_GFSR_OUT(b, v) mmio_write_32(VMIDMT_GFSR_ADDR(b), (v))
#define VMIDMT_GFSR_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_GFSR_ADDR(b), (m), (v), VMIDMT_GFSR_IN(b))

#define VMIDMT_GFSR_CLMULTI_BMSK 0x80000000
#define VMIDMT_GFSR_CLMULTI_SHFT 0x1f
#define VMIDMT_GFSR_CFGMULTI_BMSK 0x40000000
#define VMIDMT_GFSR_CFGMULTI_SHFT 0x1e
#define VMIDMT_GFSR_PF_BMSK 0x00000080
#define VMIDMT_GFSR_PF_SHFT 0x07
#define VMIDMT_GFSR_CAF_BMSK 0x00000020
#define VMIDMT_GFSR_CAF_SHFT 0x05
#define VMIDMT_GFSR_SMCF_BMSK 0x00000004
#define VMIDMT_GFSR_SMCF_SHFT 0x02
#define VMIDMT_GFSR_USF_BMSK 0x00000002
#define VMIDMT_GFSR_USF_SHFT 0x01

#define VMIDMT_NSGFSR_ADDR(b) (b + 0x00000448)
#define VMIDMT_NSGFSR_PHYS(b) (b + 0x00000448)
#define VMIDMT_NSGFSR_RMSK 0xc00000a6
#define VMIDMT_NSGFSR_SHFT 0
#define VMIDMT_NSGFSR_IN(b) \
	in_dword_masked(VMIDMT_NSGFSR_ADDR(b), VMIDMT_NSGFSR_RMSK)
#define VMIDMT_NSGFSR_INM(b, m) in_dword_masked(VMIDMT_NSGFSR_ADDR(b), (m))
#define VMIDMT_NSGFSR_OUT(b, v) mmio_write_32(VMIDMT_NSGFSR_ADDR(b), (v))
#define VMIDMT_NSGFSR_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_NSGFSR_ADDR(b), (m), (v), \
			    VMIDMT_NSGFSR_IN(b))

#define VMIDMT_NSGFSR_CLMULTI_BMSK 0x80000000
#define VMIDMT_NSGFSR_CLMULTI_SHFT 0x1f
#define VMIDMT_NSGFSR_CFGMULTI_BMSK 0x40000000
#define VMIDMT_NSGFSR_CFGMULTI_SHFT 0x1e
#define VMIDMT_NSGFSR_PF_BMSK 0x00000080
#define VMIDMT_NSGFSR_PF_SHFT 0x07
#define VMIDMT_NSGFSR_CAF_BMSK 0x00000020
#define VMIDMT_NSGFSR_CAF_SHFT 0x05
#define VMIDMT_NSGFSR_SMCF_BMSK 0x00000004
#define VMIDMT_NSGFSR_SMCF_SHFT 0x02
#define VMIDMT_NSGFSR_USF_BMSK 0x00000002
#define VMIDMT_NSGFSR_USF_SHFT 0x01

#define VMIDMT_SGFSRRESTORE_ADDR(b) (b + 0x0000004c)
#define VMIDMT_SGFSRRESTORE_PHYS(b) (b + 0x0000004c)
#define VMIDMT_SGFSRRESTORE_RMSK 0xc00000a6
#define VMIDMT_SGFSRRESTORE_SHFT 0
#define VMIDMT_SGFSRRESTORE_IN(b) \
	in_dword_masked(VMIDMT_SGFSRRESTORE_ADDR(b), VMIDMT_SGFSRRESTORE_RMSK)
#define VMIDMT_SGFSRRESTORE_INM(b, m) \
	in_dword_masked(VMIDMT_SGFSRRESTORE_ADDR(b), (m))
#define VMIDMT_SGFSRRESTORE_OUT(b, v) \
	mmio_write_32(VMIDMT_SGFSRRESTORE_ADDR(b), (v))
#define VMIDMT_SGFSRRESTORE_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_SGFSRRESTORE_ADDR(b), (m), (v), \
			    VMIDMT_SGFSRRESTORE_IN(b))

#define VMIDMT_SGFSRRESTORE_CLMULTI_BMSK 0x80000000
#define VMIDMT_SGFSRRESTORE_CLMULTI_SHFT 0x1f
#define VMIDMT_SGFSRRESTORE_CFGMULTI_BMSK 0x40000000
#define VMIDMT_SGFSRRESTORE_CFGMULTI_SHFT 0x1e
#define VMIDMT_SGFSRRESTORE_PF_BMSK 0x00000080
#define VMIDMT_SGFSRRESTORE_PF_SHFT 0x07
#define VMIDMT_SGFSRRESTORE_CAF_BMSK 0x00000020
#define VMIDMT_SGFSRRESTORE_CAF_SHFT 0x05
#define VMIDMT_SGFSRRESTORE_SMCF_BMSK 0x00000004
#define VMIDMT_SGFSRRESTORE_SMCF_SHFT 0x02
#define VMIDMT_SGFSRRESTORE_USF_BMSK 0x00000002
#define VMIDMT_SGFSRRESTORE_USF_SHFT 0x01

#define VMIDMT_GFSRRESTORE_ADDR(b) (b + 0x0000004c)
#define VMIDMT_GFSRRESTORE_PHYS(b) (b + 0x0000004c)
#define VMIDMT_GFSRRESTORE_RMSK 0xc00000a6
#define VMIDMT_GFSRRESTORE_SHFT 0
#define VMIDMT_GFSRRESTORE_IN(b) \
	in_dword_masked(VMIDMT_GFSRRESTORE_ADDR(b), VMIDMT_GFSRRESTORE_RMSK)
#define VMIDMT_GFSRRESTORE_INM(b, m) \
	in_dword_masked(VMIDMT_GFSRRESTORE_ADDR(b), (m))
#define VMIDMT_GFSRRESTORE_OUT(b, v) \
	mmio_write_32(VMIDMT_GFSRRESTORE_ADDR(b), (v))
#define VMIDMT_GFSRRESTORE_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_GFSRRESTORE_ADDR(b), (m), (v), \
			    VMIDMT_GFSRRESTORE_IN(b))

#define VMIDMT_GFSRRESTORE_CLMULTI_BMSK 0x80000000
#define VMIDMT_GFSRRESTORE_CLMULTI_SHFT 0x1f
#define VMIDMT_GFSRRESTORE_CFGMULTI_BMSK 0x40000000
#define VMIDMT_GFSRRESTORE_CFGMULTI_SHFT 0x1e
#define VMIDMT_GFSRRESTORE_PF_BMSK 0x00000080
#define VMIDMT_GFSRRESTORE_PF_SHFT 0x07
#define VMIDMT_GFSRRESTORE_CAF_BMSK 0x00000020
#define VMIDMT_GFSRRESTORE_CAF_SHFT 0x05
#define VMIDMT_GFSRRESTORE_SMCF_BMSK 0x00000004
#define VMIDMT_GFSRRESTORE_SMCF_SHFT 0x02
#define VMIDMT_GFSRRESTORE_USF_BMSK 0x00000002
#define VMIDMT_GFSRRESTORE_USF_SHFT 0x01

#define VMIDMT_NSGFSRRESTORE_ADDR(b) (b + 0x0000044c)
#define VMIDMT_NSGFSRRESTORE_PHYS(b) (b + 0x0000044c)
#define VMIDMT_NSGFSRRESTORE_RMSK 0xc00000a6
#define VMIDMT_NSGFSRRESTORE_SHFT 0
#define VMIDMT_NSGFSRRESTORE_IN(b) \
	in_dword_masked(VMIDMT_NSGFSRRESTORE_ADDR(b), VMIDMT_NSGFSRRESTORE_RMSK)
#define VMIDMT_NSGFSRRESTORE_INM(b, m) \
	in_dword_masked(VMIDMT_NSGFSRRESTORE_ADDR(b), (m))
#define VMIDMT_NSGFSRRESTORE_OUT(b, v) \
	mmio_write_32(VMIDMT_NSGFSRRESTORE_ADDR(b), (v))
#define VMIDMT_NSGFSRRESTORE_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_NSGFSRRESTORE_ADDR(b), (m), (v), \
			    VMIDMT_NSGFSRRESTORE_IN(b))

#define VMIDMT_NSGFSRRESTORE_CLMULTI_BMSK 0x80000000
#define VMIDMT_NSGFSRRESTORE_CLMULTI_SHFT 0x1f
#define VMIDMT_NSGFSRRESTORE_CFGMULTI_BMSK 0x40000000
#define VMIDMT_NSGFSRRESTORE_CFGMULTI_SHFT 0x1e
#define VMIDMT_NSGFSRRESTORE_PF_BMSK 0x00000080
#define VMIDMT_NSGFSRRESTORE_PF_SHFT 0x07
#define VMIDMT_NSGFSRRESTORE_CAF_BMSK 0x00000020
#define VMIDMT_NSGFSRRESTORE_CAF_SHFT 0x05
#define VMIDMT_NSGFSRRESTORE_SMCF_BMSK 0x00000004
#define VMIDMT_NSGFSRRESTORE_SMCF_SHFT 0x02
#define VMIDMT_NSGFSRRESTORE_USF_BMSK 0x00000002
#define VMIDMT_NSGFSRRESTORE_USF_SHFT 0x01

#define VMIDMT_SGFSYNDR0_ADDR(b) (b + 0x00000050)
#define VMIDMT_SGFSYNDR0_PHYS(b) (b + 0x00000050)
#define VMIDMT_SGFSYNDR0_RMSK 0x000001ff
#define VMIDMT_SGFSYNDR0_SHFT 0
#define VMIDMT_SGFSYNDR0_IN(b) \
	in_dword_masked(VMIDMT_SGFSYNDR0_ADDR(b), VMIDMT_SGFSYNDR0_RMSK)
#define VMIDMT_SGFSYNDR0_INM(b, m) \
	in_dword_masked(VMIDMT_SGFSYNDR0_ADDR(b), (m))

#define VMIDMT_SGFSYNDR0_MSA_STATE_BMSK 0x00000100
#define VMIDMT_SGFSYNDR0_MSA_STATE_SHFT 0x08
#define VMIDMT_SGFSYNDR0_NSATTR_BMSK 0x00000020
#define VMIDMT_SGFSYNDR0_NSATTR_SHFT 0x05
#define VMIDMT_SGFSYNDR0_NSSTATE_BMSK 0x00000010
#define VMIDMT_SGFSYNDR0_NSSTATE_SHFT 0x04
#define VMIDMT_SGFSYNDR0_WNR_BMSK 0x00000002
#define VMIDMT_SGFSYNDR0_WNR_SHFT 0x01

#define VMIDMT_GFSYNDR0_ADDR(b) (b + 0x00000050)
#define VMIDMT_GFSYNDR0_PHYS(b) (b + 0x00000050)
#define VMIDMT_GFSYNDR0_RMSK 0x000001ff
#define VMIDMT_GFSYNDR0_SHFT 0
#define VMIDMT_GFSYNDR0_IN(b) \
	in_dword_masked(VMIDMT_GFSYNDR0_ADDR(b), VMIDMT_GFSYNDR0_RMSK)
#define VMIDMT_GFSYNDR0_INM(b, m) in_dword_masked(VMIDMT_GFSYNDR0_ADDR(b), (m))

#define VMIDMT_GFSYNDR0_MSA_STATE_BMSK 0x00000100
#define VMIDMT_GFSYNDR0_MSA_STATE_SHFT 0x08
#define VMIDMT_GFSYNDR0_NSATTR_BMSK 0x00000020
#define VMIDMT_GFSYNDR0_NSATTR_SHFT 0x05
#define VMIDMT_GFSYNDR0_NSSTATE_BMSK 0x00000010
#define VMIDMT_GFSYNDR0_NSSTATE_SHFT 0x04
#define VMIDMT_GFSYNDR0_WNR_BMSK 0x00000002
#define VMIDMT_GFSYNDR0_WNR_SHFT 0x01

#define VMIDMT_NSGFSYNDR0_ADDR(b) (b + 0x00000450)
#define VMIDMT_NSGFSYNDR0_PHYS(b) (b + 0x00000450)
#define VMIDMT_NSGFSYNDR0_RMSK 0x000001ff
#define VMIDMT_NSGFSYNDR0_SHFT 0
#define VMIDMT_NSGFSYNDR0_IN(b) \
	in_dword_masked(VMIDMT_NSGFSYNDR0_ADDR(b), VMIDMT_NSGFSYNDR0_RMSK)
#define VMIDMT_NSGFSYNDR0_INM(b, m) \
	in_dword_masked(VMIDMT_NSGFSYNDR0_ADDR(b), (m))

#define VMIDMT_NSGFSYNDR0_MSA_STATE_BMSK 0x00000100
#define VMIDMT_NSGFSYNDR0_MSA_STATE_SHFT 0x08
#define VMIDMT_NSGFSYNDR0_NSATTR_BMSK 0x00000020
#define VMIDMT_NSGFSYNDR0_NSATTR_SHFT 0x05
#define VMIDMT_NSGFSYNDR0_NSSTATE_BMSK 0x00000010
#define VMIDMT_NSGFSYNDR0_NSSTATE_SHFT 0x04
#define VMIDMT_NSGFSYNDR0_WNR_BMSK 0x00000002
#define VMIDMT_NSGFSYNDR0_WNR_SHFT 0x01

#define VMIDMT_SGFSYNDR1_ADDR(b) (b + 0x00000054)
#define VMIDMT_SGFSYNDR1_PHYS(b) (b + 0x00000054)
#define VMIDMT_SGFSYNDR1_RMSK 0xffffffff
#define VMIDMT_SGFSYNDR1_SHFT 0
#define VMIDMT_SGFSYNDR1_IN(b) \
	in_dword_masked(VMIDMT_SGFSYNDR1_ADDR(b), VMIDMT_SGFSYNDR1_RMSK)
#define VMIDMT_SGFSYNDR1_INM(b, m) \
	in_dword_masked(VMIDMT_SGFSYNDR1_ADDR(b), (m))

#define VMIDMT_SGFSYNDR1_MSD_INDEX_BMSK 0xff000000
#define VMIDMT_SGFSYNDR1_MSD_INDEX_SHFT 0x18
#define VMIDMT_SGFSYNDR1_SSD_INDEX_BMSK 0x00ff0000
#define VMIDMT_SGFSYNDR1_SSD_INDEX_SHFT 0x10
#define VMIDMT_SGFSYNDR1_SID_BMSK 0x00007fff
#define VMIDMT_SGFSYNDR1_SID_SHFT 0x00

#define VMIDMT_GFSYNDR1_ADDR(b) (b + 0x00000054)
#define VMIDMT_GFSYNDR1_PHYS(b) (b + 0x00000054)
#define VMIDMT_GFSYNDR1_RMSK 0xffffffff
#define VMIDMT_GFSYNDR1_SHFT 0
#define VMIDMT_GFSYNDR1_IN(b) \
	in_dword_masked(VMIDMT_GFSYNDR1_ADDR(b), VMIDMT_GFSYNDR1_RMSK)
#define VMIDMT_GFSYNDR1_INM(b, m) in_dword_masked(VMIDMT_GFSYNDR1_ADDR(b), (m))

#define VMIDMT_GFSYNDR1_MSD_INDEX_BMSK 0xff000000
#define VMIDMT_GFSYNDR1_MSD_INDEX_SHFT 0x18
#define VMIDMT_GFSYNDR1_SSD_INDEX_BMSK 0x00ff0000
#define VMIDMT_GFSYNDR1_SSD_INDEX_SHFT 0x10
#define VMIDMT_GFSYNDR1_SID_BMSK 0x00007fff
#define VMIDMT_GFSYNDR1_SID_SHFT 0x00

#define VMIDMT_NSGFSYNDR1_ADDR(b) (b + 0x00000454)
#define VMIDMT_NSGFSYNDR1_PHYS(b) (b + 0x00000454)
#define VMIDMT_NSGFSYNDR1_RMSK 0xffffffff
#define VMIDMT_NSGFSYNDR1_SHFT 0
#define VMIDMT_NSGFSYNDR1_IN(b) \
	in_dword_masked(VMIDMT_NSGFSYNDR1_ADDR(b), VMIDMT_NSGFSYNDR1_RMSK)
#define VMIDMT_NSGFSYNDR1_INM(b, m) \
	in_dword_masked(VMIDMT_NSGFSYNDR1_ADDR(b), (m))

#define VMIDMT_NSGFSYNDR1_MSD_INDEX_BMSK 0xff000000
#define VMIDMT_NSGFSYNDR1_MSD_INDEX_SHFT 0x18
#define VMIDMT_NSGFSYNDR1_SSD_INDEX_BMSK 0x00ff0000
#define VMIDMT_NSGFSYNDR1_SSD_INDEX_SHFT 0x10
#define VMIDMT_NSGFSYNDR1_SID_BMSK 0x00007fff
#define VMIDMT_NSGFSYNDR1_SID_SHFT 0x00

#define VMIDMT_SGFSYNDR2_ADDR(b) (b + 0x00000058)
#define VMIDMT_SGFSYNDR2_PHYS(b) (b + 0x00000058)
#define VMIDMT_SGFSYNDR2_RMSK 0xffffffff
#define VMIDMT_SGFSYNDR2_SHFT 0
#define VMIDMT_SGFSYNDR2_IN(b) \
	in_dword_masked(VMIDMT_SGFSYNDR2_ADDR(b), VMIDMT_SGFSYNDR2_RMSK)
#define VMIDMT_SGFSYNDR2_INM(b, m) \
	in_dword_masked(VMIDMT_SGFSYNDR2_ADDR(b), (m))

#define VMIDMT_SGFSYNDR2_ATID_BMSK 0xff000000
#define VMIDMT_SGFSYNDR2_ATID_SHFT 0x18
#define VMIDMT_SGFSYNDR2_AVMID_BMSK 0x00ff0000
#define VMIDMT_SGFSYNDR2_AVMID_SHFT 0x10
#define VMIDMT_SGFSYNDR2_ABID_BMSK 0x0000e000
#define VMIDMT_SGFSYNDR2_ABID_SHFT 0x0d
#define VMIDMT_SGFSYNDR2_APID_BMSK 0x00001f00
#define VMIDMT_SGFSYNDR2_APID_SHFT 0x08
#define VMIDMT_SGFSYNDR2_AMID_BMSK 0x000000ff
#define VMIDMT_SGFSYNDR2_AMID_SHFT 0x00

#define VMIDMT_GFSYNDR2_ADDR(b) (b + 0x00000058)
#define VMIDMT_GFSYNDR2_PHYS(b) (b + 0x00000058)
#define VMIDMT_GFSYNDR2_RMSK 0xffffffff
#define VMIDMT_GFSYNDR2_SHFT 0
#define VMIDMT_GFSYNDR2_IN(b) \
	in_dword_masked(VMIDMT_GFSYNDR2_ADDR(b), VMIDMT_GFSYNDR2_RMSK)
#define VMIDMT_GFSYNDR2_INM(b, m) in_dword_masked(VMIDMT_GFSYNDR2_ADDR(b), (m))

#define VMIDMT_GFSYNDR2_ATID_BMSK 0xff000000
#define VMIDMT_GFSYNDR2_ATID_SHFT 0x18
#define VMIDMT_GFSYNDR2_AVMID_BMSK 0x00ff0000
#define VMIDMT_GFSYNDR2_AVMID_SHFT 0x10
#define VMIDMT_GFSYNDR2_ABID_BMSK 0x0000e000
#define VMIDMT_GFSYNDR2_ABID_SHFT 0x0d
#define VMIDMT_GFSYNDR2_APID_BMSK 0x00001f00
#define VMIDMT_GFSYNDR2_APID_SHFT 0x08
#define VMIDMT_GFSYNDR2_AMID_BMSK 0x000000ff
#define VMIDMT_GFSYNDR2_AMID_SHFT 0x00

#define VMIDMT_NSGFSYNDR2_ADDR(b) (b + 0x00000458)
#define VMIDMT_NSGFSYNDR2_PHYS(b) (b + 0x00000458)
#define VMIDMT_NSGFSYNDR2_RMSK 0xffffffff
#define VMIDMT_NSGFSYNDR2_SHFT 0
#define VMIDMT_NSGFSYNDR2_IN(b) \
	in_dword_masked(VMIDMT_NSGFSYNDR2_ADDR(b), VMIDMT_NSGFSYNDR2_RMSK)
#define VMIDMT_NSGFSYNDR2_INM(b, m) \
	in_dword_masked(VMIDMT_NSGFSYNDR2_ADDR(b), (m))

#define VMIDMT_NSGFSYNDR2_ATID_BMSK 0xff000000
#define VMIDMT_NSGFSYNDR2_ATID_SHFT 0x18
#define VMIDMT_NSGFSYNDR2_AVMID_BMSK 0x00ff0000
#define VMIDMT_NSGFSYNDR2_AVMID_SHFT 0x10
#define VMIDMT_NSGFSYNDR2_ABID_BMSK 0x0000e000
#define VMIDMT_NSGFSYNDR2_ABID_SHFT 0x0d
#define VMIDMT_NSGFSYNDR2_APID_BMSK 0x00001f00
#define VMIDMT_NSGFSYNDR2_APID_SHFT 0x08
#define VMIDMT_NSGFSYNDR2_AMID_BMSK 0x000000ff
#define VMIDMT_NSGFSYNDR2_AMID_SHFT 0x00

#define VMIDMT_SSDRn_ADDR(b, n) (b + 0x00000080 + 4 * (n))
#define VMIDMT_SSDRn_PHYS(b, n) (b + 0x00000080 + 4 * (n))
#define VMIDMT_SSDRn_RMSK 0xffffffff
#define VMIDMT_SSDRn_SHFT 0
#define VMIDMT_SSDRn_INI(b, n) mmio_read_32(VMIDMT_SSDRn_ADDR(b, (n)))
#define VMIDMT_SSDRn_INMI(b, n, mask) \
	in_dword_masked(VMIDMT_SSDRn_ADDR(b, (n)), (mask))
#define VMIDMT_SSDRn_OUTI(b, n, val) \
	mmio_write_32(VMIDMT_SSDRn_ADDR(b, (n)), (val))
#define VMIDMT_SSDRn_OUTMI(b, n, mask, val)                           \
	out_dword_masked_ns(VMIDMT_SSDRn_ADDR(b, (n)), (mask), (val), \
			    VMIDMT_SSDRn_INI(b, (n)))

#define VMIDMT_SSDRn_NS_STATE_BMSK 0xffffffff
#define VMIDMT_SSDRn_NS_STATE_SHFT 0x00

#define VMIDMT_SVMIDMTCR0_ADDR(b) (b + 0x00000090)
#define VMIDMT_SVMIDMTCR0_PHYS(b) (b + 0x00000090)
#define VMIDMT_SVMIDMTCR0_RMSK 0x00000001
#define VMIDMT_SVMIDMTCR0_SHFT 0
#define VMIDMT_SVMIDMTCR0_IN(b) \
	in_dword_masked(VMIDMT_SVMIDMTCR0_ADDR(b), VMIDMT_SVMIDMTCR0_RMSK)
#define VMIDMT_SVMIDMTCR0_INM(b, m) \
	in_dword_masked(VMIDMT_SVMIDMTCR0_ADDR(b), (m))
#define VMIDMT_SVMIDMTCR0_OUT(b, v) \
	mmio_write_32(VMIDMT_SVMIDMTCR0_ADDR(b), (v))
#define VMIDMT_SVMIDMTCR0_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_SVMIDMTCR0_ADDR(b), (m), (v), \
			    VMIDMT_SVMIDMTCR0_IN(b))

#define VMIDMT_SVMIDMTCR0_CLKONOFFE_BMSK 0x00000001
#define VMIDMT_SVMIDMTCR0_CLKONOFFE_SHFT 0x00

#define VMIDMT_VMIDMTCR0_ADDR(b) (b + 0x00000090)
#define VMIDMT_VMIDMTCR0_PHYS(b) (b + 0x00000090)
#define VMIDMT_VMIDMTCR0_RMSK 0x00000001
#define VMIDMT_VMIDMTCR0_SHFT 0
#define VMIDMT_VMIDMTCR0_IN(b) \
	in_dword_masked(VMIDMT_VMIDMTCR0_ADDR(b), VMIDMT_VMIDMTCR0_RMSK)
#define VMIDMT_VMIDMTCR0_INM(b, m) \
	in_dword_masked(VMIDMT_VMIDMTCR0_ADDR(b), (m))
#define VMIDMT_VMIDMTCR0_OUT(b, v) mmio_write_32(VMIDMT_VMIDMTCR0_ADDR(b), (v))
#define VMIDMT_VMIDMTCR0_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_VMIDMTCR0_ADDR(b), (m), (v), \
			    VMIDMT_VMIDMTCR0_IN(b))

#define VMIDMT_VMIDMTCR0_CLKONOFFE_BMSK 0x00000001
#define VMIDMT_VMIDMTCR0_CLKONOFFE_SHFT 0x00

#define VMIDMT_NSVMIDMTCR0_ADDR(b) (b + 0x00000490)
#define VMIDMT_NSVMIDMTCR0_PHYS(b) (b + 0x00000490)
#define VMIDMT_NSVMIDMTCR0_RMSK 0x00000001
#define VMIDMT_NSVMIDMTCR0_SHFT 0
#define VMIDMT_NSVMIDMTCR0_IN(b) \
	in_dword_masked(VMIDMT_NSVMIDMTCR0_ADDR(b), VMIDMT_NSVMIDMTCR0_RMSK)
#define VMIDMT_NSVMIDMTCR0_INM(b, m) \
	in_dword_masked(VMIDMT_NSVMIDMTCR0_ADDR(b), (m))
#define VMIDMT_NSVMIDMTCR0_OUT(b, v) \
	mmio_write_32(VMIDMT_NSVMIDMTCR0_ADDR(b), (v))
#define VMIDMT_NSVMIDMTCR0_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_NSVMIDMTCR0_ADDR(b), (m), (v), \
			    VMIDMT_NSVMIDMTCR0_IN(b))

#define VMIDMT_NSVMIDMTCR0_CLKONOFFE_BMSK 0x00000001
#define VMIDMT_NSVMIDMTCR0_CLKONOFFE_SHFT 0x00

#define VMIDMT_VMIDMTACR_ADDR(b) (b + 0x0000009c)
#define VMIDMT_VMIDMTACR_PHYS(b) (b + 0x0000009c)
#define VMIDMT_VMIDMTACR_RMSK 0xffffffff
#define VMIDMT_VMIDMTACR_SHFT 0
#define VMIDMT_VMIDMTACR_IN(b) \
	in_dword_masked(VMIDMT_VMIDMTACR_ADDR(b), VMIDMT_VMIDMTACR_RMSK)
#define VMIDMT_VMIDMTACR_INM(b, m) \
	in_dword_masked(VMIDMT_VMIDMTACR_ADDR(b), (m))
#define VMIDMT_VMIDMTACR_OUT(b, v) mmio_write_32(VMIDMT_VMIDMTACR_ADDR(b), (v))
#define VMIDMT_VMIDMTACR_OUTM(b, m, v)                          \
	out_dword_masked_ns(VMIDMT_VMIDMTACR_ADDR(b), (m), (v), \
			    VMIDMT_VMIDMTACR_IN(b))

#define VMIDMT_VMIDMTACR_VMID_BMSK 0xffffffff
#define VMIDMT_VMIDMTACR_VMID_SHFT 0x00

#define VMIDMT_MSD0_ADDR(b) (b + 0x00000480)
#define VMIDMT_MSD0_PHYS(b) (b + 0x00000480)
#define VMIDMT_MSD0_RMSK 0xffffffff
#define VMIDMT_MSD0_SHFT 0
#define VMIDMT_MSD0_IN(b) in_dword_masked(VMIDMT_MSD0_ADDR(b), VMIDMT_MSD0_RMSK)
#define VMIDMT_MSD0_INM(b, m) in_dword_masked(VMIDMT_MSD0_ADDR(b), (m))
#define VMIDMT_MSD0_OUT(b, v) mmio_write_32(VMIDMT_MSD0_ADDR(b), (v))
#define VMIDMT_MSD0_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_MSD0_ADDR(b), (m), (v), VMIDMT_MSD0_IN(b))

#define VMIDMT_MSD0_MSA_STATE_BMSK 0xffffffff
#define VMIDMT_MSD0_MSA_STATE_SHFT 0x00

#define VMIDMT_MSD1_ADDR(b) (b + 0x00000484)
#define VMIDMT_MSD1_PHYS(b) (b + 0x00000484)
#define VMIDMT_MSD1_RMSK 0xffffffff
#define VMIDMT_MSD1_SHFT 0
#define VMIDMT_MSD1_IN(b) in_dword_masked(VMIDMT_MSD1_ADDR(b), VMIDMT_MSD1_RMSK)
#define VMIDMT_MSD1_INM(b, m) in_dword_masked(VMIDMT_MSD1_ADDR(b), (m))
#define VMIDMT_MSD1_OUT(b, v) mmio_write_32(VMIDMT_MSD1_ADDR(b), (v))
#define VMIDMT_MSD1_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_MSD1_ADDR(b), (m), (v), VMIDMT_MSD1_IN(b))

#define VMIDMT_MSD1_MSA_STATE_BMSK 0xffffffff
#define VMIDMT_MSD1_MSA_STATE_SHFT 0x00

#define VMIDMT_MSD2_ADDR(b) (b + 0x00000488)
#define VMIDMT_MSD2_PHYS(b) (b + 0x00000488)
#define VMIDMT_MSD2_RMSK 0xffffffff
#define VMIDMT_MSD2_SHFT 0
#define VMIDMT_MSD2_IN(b) in_dword_masked(VMIDMT_MSD2_ADDR(b), VMIDMT_MSD2_RMSK)
#define VMIDMT_MSD2_INM(b, m) in_dword_masked(VMIDMT_MSD2_ADDR(b), (m))
#define VMIDMT_MSD2_OUT(b, v) mmio_write_32(VMIDMT_MSD2_ADDR(b), (v))
#define VMIDMT_MSD2_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_MSD2_ADDR(b), (m), (v), VMIDMT_MSD2_IN(b))

#define VMIDMT_MSD2_MSA_STATE_BMSK 0xffffffff
#define VMIDMT_MSD2_MSA_STATE_SHFT 0x00

#define VMIDMT_MSD3_ADDR(b) (b + 0x0000048c)
#define VMIDMT_MSD3_PHYS(b) (b + 0x0000048c)
#define VMIDMT_MSD3_RMSK 0xffffffff
#define VMIDMT_MSD3_SHFT 0
#define VMIDMT_MSD3_IN(b) in_dword_masked(VMIDMT_MSD3_ADDR(b), VMIDMT_MSD3_RMSK)
#define VMIDMT_MSD3_INM(b, m) in_dword_masked(VMIDMT_MSD3_ADDR(b), (m))
#define VMIDMT_MSD3_OUT(b, v) mmio_write_32(VMIDMT_MSD3_ADDR(b), (v))
#define VMIDMT_MSD3_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_MSD3_ADDR(b), (m), (v), VMIDMT_MSD3_IN(b))

#define VMIDMT_MSD3_MSA_STATE_BMSK 0xffffffff
#define VMIDMT_MSD3_MSA_STATE_SHFT 0x00

#define VMIDMT_MCR_ADDR(b) (b + 0x00000494)
#define VMIDMT_MCR_PHYS(b) (b + 0x00000494)
#define VMIDMT_MCR_RMSK 0x00000007
#define VMIDMT_MCR_SHFT 0
#define VMIDMT_MCR_IN(b) in_dword_masked(VMIDMT_MCR_ADDR(b), VMIDMT_MCR_RMSK)
#define VMIDMT_MCR_INM(b, m) in_dword_masked(VMIDMT_MCR_ADDR(b), (m))
#define VMIDMT_MCR_OUT(b, v) mmio_write_32(VMIDMT_MCR_ADDR(b), (v))
#define VMIDMT_MCR_OUTM(b, m, v) \
	out_dword_masked_ns(VMIDMT_MCR_ADDR(b), (m), (v), VMIDMT_MCR_IN(b))

#define VMIDMT_MCR_CLKONOFFE_BMSK 0x00000004
#define VMIDMT_MCR_CLKONOFFE_SHFT 0x02
#define VMIDMT_MCR_BPMSACFG_BMSK 0x00000002
#define VMIDMT_MCR_BPMSACFG_SHFT 0x01
#define VMIDMT_MCR_BPSMSACFG_BMSK 0x00000001
#define VMIDMT_MCR_BPSMSACFG_SHFT 0x00

#define VMIDMT_SMRn_ADDR(b, n) (b + 0x00000800 + 4 * (n))
#define VMIDMT_SMRn_PHYS(b, n) (b + 0x00000800 + 4 * (n))
#define VMIDMT_SMRn_RMSK 0xffffffff
#define VMIDMT_SMRn_SHFT 0
#define VMIDMT_SMRn_INI(b, n) mmio_read_32(VMIDMT_SMRn_ADDR(b, (n)))
#define VMIDMT_SMRn_INMI(b, n, mask) \
	in_dword_masked(VMIDMT_SMRn_ADDR(b, (n)), (mask))
#define VMIDMT_SMRn_OUTI(b, n, val) \
	mmio_write_32(VMIDMT_SMRn_ADDR(b, (n)), (val))
#define VMIDMT_SMRn_OUTMI(b, n, mask, val)                           \
	out_dword_masked_ns(VMIDMT_SMRn_ADDR(b, (n)), (mask), (val), \
			    VMIDMT_SMRn_INI(b, (n)))

#define VMIDMT_SMRn_VALID_BMSK 0x80000000
#define VMIDMT_SMRn_VALID_SHFT 0x1f
#define VMIDMT_SMRn_MASK_BMSK 0x7fff0000
#define VMIDMT_SMRn_MASK_SHFT 0x10
#define VMIDMT_SMRn_ID_BMSK 0x00007fff
#define VMIDMT_SMRn_ID_SHFT 0x00

#define VMIDMT_S2VRn_ADDR(b, n) (b + 0x00000c00 + 4 * (n))
#define VMIDMT_S2VRn_PHYS(b, n) (b + 0x00000c00 + 4 * (n))
#define VMIDMT_S2VRn_RMSK 0x30fcfbff
#define VMIDMT_S2VRn_SHFT 0
#define VMIDMT_S2VRn_INI(b, n) mmio_read_32(VMIDMT_S2VRn_ADDR(b, (n)))
#define VMIDMT_S2VRn_INMI(b, n, mask) \
	in_dword_masked(VMIDMT_S2VRn_ADDR(b, (n)), (mask))
#define VMIDMT_S2VRn_OUTI(b, n, val) \
	mmio_write_32(VMIDMT_S2VRn_ADDR(b, (n)), (val))
#define VMIDMT_S2VRn_OUTMI(b, n, mask, val)                           \
	out_dword_masked_ns(VMIDMT_S2VRn_ADDR(b, (n)), (mask), (val), \
			    VMIDMT_S2VRn_INI(b, (n)))

#define VMIDMT_S2VRn_TRANSIENTCFG_BMSK 0x30000000
#define VMIDMT_S2VRn_TRANSIENTCFG_SHFT 0x1c
#define VMIDMT_S2VRn_WACFG_BMSK 0x00c00000
#define VMIDMT_S2VRn_WACFG_SHFT 0x16
#define VMIDMT_S2VRn_RACFG_BMSK 0x00300000
#define VMIDMT_S2VRn_RACFG_SHFT 0x14
#define VMIDMT_S2VRn_NSCFG_BMSK 0x000c0000
#define VMIDMT_S2VRn_NSCFG_SHFT 0x12
#define VMIDMT_S2VRn_TYPE_BMSK 0x00030000
#define VMIDMT_S2VRn_TYPE_SHFT 0x10
#define VMIDMT_S2VRn_MEMATTR_BMSK 0x0000f000
#define VMIDMT_S2VRn_MEMATTR_SHFT 0x0c
#define VMIDMT_S2VRn_MTCFG_BMSK 0x00000800
#define VMIDMT_S2VRn_MTCFG_SHFT 0x0b
#define VMIDMT_S2VRn_SHCFG_BMSK 0x00000300
#define VMIDMT_S2VRn_SHCFG_SHFT 0x08
#define VMIDMT_S2VRn_VMID_BMSK 0x000000ff
#define VMIDMT_S2VRn_VMID_SHFT 0x00

#define VMIDMT_AS2VRn_ADDR(b, n) (b + 0x00000e00 + 4 * (n))
#define VMIDMT_AS2VRn_PHYS(b, n) (b + 0x00000e00 + 4 * (n))
#define VMIDMT_AS2VRn_RMSK 0x70000013
#define VMIDMT_AS2VRn_SHFT 0
#define VMIDMT_AS2VRn_INI(b, n) mmio_read_32(VMIDMT_AS2VRn_ADDR(b, (n)))
#define VMIDMT_AS2VRn_INMI(b, n, mask) \
	in_dword_masked(VMIDMT_AS2VRn_ADDR(b, (n)), (mask))
#define VMIDMT_AS2VRn_OUTI(b, n, val) \
	mmio_write_32(VMIDMT_AS2VRn_ADDR(b, (n)), (val))
#define VMIDMT_AS2VRn_OUTMI(b, n, mask, val)                           \
	out_dword_masked_ns(VMIDMT_AS2VRn_ADDR(b, (n)), (mask), (val), \
			    VMIDMT_AS2VRn_INI(b, (n)))

#define VMIDMT_AS2VRn_RCNSH_BMSK 0x40000000
#define VMIDMT_AS2VRn_RCNSH_SHFT 0x1e
#define VMIDMT_AS2VRn_RCISH_BMSK 0x20000000
#define VMIDMT_AS2VRn_RCISH_SHFT 0x1d
#define VMIDMT_AS2VRn_RCOSH_BMSK 0x10000000
#define VMIDMT_AS2VRn_RCOSH_SHFT 0x1c
#define VMIDMT_AS2VRn_REQPRIORITYCFG_BMSK 0x00000010
#define VMIDMT_AS2VRn_REQPRIORITYCFG_SHFT 0x04
#define VMIDMT_AS2VRn_REQPRIORITY_BMSK 0x00000003
#define VMIDMT_AS2VRn_REQPRIORITY_SHFT 0x00

#define VMIDMT_IN(base, regsym) __vmidmthwio_in(base, regsym)
#define VMIDMT_INI(base, regsym, index) __vmidmthwio_ini(base, regsym, index)
#define VMIDMT_INM(base, regsym, mask) __vmidmthwio_inm(base, regsym, mask)
#define VMIDMT_INMI(base, regsym, index, mask) \
	__vmidmthwio_inmi(base, regsym, index, mask)
#define VMIDMT_OUT(base, regsym, val) __vmidmthwio_out(base, regsym, val)
#define VMIDMT_OUTI(base, regsym, index, val) \
	__vmidmthwio_outi(base, regsym, index, val)
#define VMIDMT_OUTM(base, regsym, mask, val) \
	__vmidmthwio_outm(base, regsym, mask, val)
#define VMIDMT_OUTMI(base, regsym, index, mask, val) \
	__vmidmthwio_outmi(base, regsym, index, mask, val)
#define VMIDMT_ADDR(base, regsym) __vmidmthwio_addr(base, regsym)
#define VMIDMT_ADDRI(base, regsym, index) \
	__vmidmthwio_addri(base, regsym, index)
#define VMIDMT_RMSK(regsym) __vmidmthwio_rmsk(regsym)
#define VMIDMT_RSHFT(regsym) __vmidmthwio_rshft(regsym)
#define VMIDMT_SHFT(regsym, fldsym) __vmidmthwio_shft(regsym, fldsym)
#define VMIDMT_FMSK(regsym, fldsym) __vmidmthwio_fmsk(regsym, fldsym)
#define VMIDMT_INFI(base, regsym, index, field)                          \
	(VMIDMT_INMI(base, regsym, index, VMIDMT_FMSK(regsym, field)) >> \
	 VMIDMT_SHFT(regsym, field))
#define VMIDMT_OUTF(base, regsym, field, val)                 \
	VMIDMT_OUTM(base, regsym, VMIDMT_FMSK(regsym, field), \
		    (val) << VMIDMT_SHFT(regsym, field))
#define VMIDMT_INF(base, regsym, field)                          \
	(VMIDMT_INM(base, regsym, VMIDMT_FMSK(regsym, field)) >> \
	 VMIDMT_SHFT(regsym, field))
#define VMIDMT_OUTFI(base, regsym, index, field, val)                 \
	VMIDMT_OUTMI(base, regsym, index, VMIDMT_FMSK(regsym, field), \
		     (val) << VMIDMT_SHFT(regsym, field))
#define VMIDMT_INFC(regval, regsym, field) \
	(((regval) & VMIDMT_FMSK(regsym, field)) >> VMIDMT_SHFT(regsym, field))
#define __vmidmthwio_in(base, regsym) VMIDMT_##regsym##_IN(base)
#define __vmidmthwio_ini(base, regsym, index) VMIDMT_##regsym##_INI(base, index)
#define __vmidmthwio_inm(base, regsym, mask) VMIDMT_##regsym##_INM(base, mask)
#define __vmidmthwio_inmi(base, regsym, index, mask) \
	VMIDMT_##regsym##_INMI(base, index, mask)
#define __vmidmthwio_out(base, regsym, val) VMIDMT_##regsym##_OUT(base, val)
#define __vmidmthwio_outi(base, regsym, index, val) \
	VMIDMT_##regsym##_OUTI(base, index, val)
#define __vmidmthwio_outm(base, regsym, mask, val) \
	VMIDMT_##regsym##_OUTM(base, mask, val)
#define __vmidmthwio_outmi(base, regsym, index, mask, val) \
	VMIDMT_##regsym##_OUTMI(base, index, mask, val)
#define __vmidmthwio_addr(base, regsym) VMIDMT_##regsym##_ADDR(base)
#define __vmidmthwio_addri(base, regsym, index) \
	VMIDMT_##regsym##_ADDR(base, index)
#define __vmidmthwio_rmsk(regsym) VMIDMT_##regsym##_RMSK
#define __vmidmthwio_fmsk(regsym, fldsym) VMIDMT_##regsym##_##fldsym##_BMSK
#define __vmidmthwio_rshft(regsym) VMIDMT_##regsym##_SHFT
#define __vmidmthwio_shft(regsym, fldsym) VMIDMT_##regsym##_##fldsym##_SHFT

#endif /* VMIDMT_HAL_HWIO_H */
