/*
 * Copyright (c) 2025, MediaTek Inc. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef MT_AUDIO_PRIVATE_H
#define MT_AUDIO_PRIVATE_H

#include <platform_def.h>

#define AFE_SE_DOMAIN_SIDEBAND0      (AUDIO_BASE + 0x5650)
#define AFE_SE_DOMAIN_SIDEBAND1      (AUDIO_BASE + 0x5654)
#define AFE_SE_DOMAIN_SIDEBAND2      (AUDIO_BASE + 0x5658)
#define AFE_SE_DOMAIN_SIDEBAND3      (AUDIO_BASE + 0x565c)
#define AFE_SE_DOMAIN_SIDEBAND4      (AUDIO_BASE + 0x5660)
#define AFE_SE_DOMAIN_SIDEBAND5      (AUDIO_BASE + 0x5664)
#define AFE_SE_DOMAIN_SIDEBAND6      (AUDIO_BASE + 0x5668)
#define AFE_SE_DOMAIN_SIDEBAND7      (AUDIO_BASE + 0x566c)
#define AFE_SE_DOMAIN_SIDEBAND8      (AUDIO_BASE + 0x5670)
#define AFE_SE_DOMAIN_SIDEBAND9      (AUDIO_BASE + 0x5674)

#define AFE_SE_DOMAIN_SIDEBAND0_MON  (AUDIO_BASE + 0x5688)
#define AFE_SE_DOMAIN_SIDEBAND1_MON  (AUDIO_BASE + 0x568c)
#define AFE_SE_DOMAIN_SIDEBAND2_MON  (AUDIO_BASE + 0x5690)
#define AFE_SE_DOMAIN_SIDEBAND3_MON  (AUDIO_BASE + 0x5694)
#define AFE_SE_DOMAIN_SIDEBAND4_MON  (AUDIO_BASE + 0x5698)
#define AFE_SE_DOMAIN_SIDEBAND5_MON  (AUDIO_BASE + 0x569c)
#define AFE_SE_DOMAIN_SIDEBAND6_MON  (AUDIO_BASE + 0x56a0)
#define AFE_SE_DOMAIN_SIDEBAND7_MON  (AUDIO_BASE + 0x56a4)
#define AFE_SE_DOMAIN_SIDEBAND8_MON  (AUDIO_BASE + 0x56a8)
#define AFE_SE_DOMAIN_SIDEBAND9_MON  (AUDIO_BASE + 0x56ac)

#endif /* MT_AUDIO_PRIVATE_H */
