/*
 * Copyright (c) 2022-2025 Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier:    BSD-3-Clause
 */

#include <stdint.h>
#include <stdlib.h>

#include <plat/common/platform.h>
#include <services/drtm_svc.h>
#include <platform_def.h>

/* Address map revision generated by this code. */
#define DRTM_ADDRESS_MAP_REVISION	U(0x0001)

/* Amount of space needed for address map based on PLAT_DRTM_MMAP_ENTRIES */
#define DRTM_ADDRESS_MAP_SIZE (sizeof(drtm_memory_region_descriptor_table_t) + \
			       (sizeof(drtm_mem_region_t) * \
				PLAT_DRTM_MMAP_ENTRIES))

/* Allocate space for DRTM-formatted address map to be constructed. */
static uint8_t drtm_address_map[DRTM_ADDRESS_MAP_SIZE];

static uint64_t drtm_address_map_size;

static int compare_regions(const void *a, const void *b)
{
	const drtm_mem_region_t *region_a = (const drtm_mem_region_t *)a;
	const drtm_mem_region_t *region_b = (const drtm_mem_region_t *)b;

	if (region_a->region_address < region_b->region_address) {
		return -1;
	} else if (region_a->region_address > region_b->region_address) {
		return 1;
	} else {
		return 0;
	}
}

static void coalesce_regions(drtm_memory_region_descriptor_table_t *map)
{
	const uint64_t page_count_mask =
		ARM_DRTM_REGION_SIZE_TYPE_4K_PAGE_NUM_MASK <<
		ARM_DRTM_REGION_SIZE_TYPE_4K_PAGE_NUM_SHIFT;
	unsigned int read_index;
	unsigned int write_index = 0U;

	for (read_index = 0U; read_index < map->num_regions; read_index++) {
		drtm_mem_region_t *current = &map->region[read_index];

		/* Check if write index can be coalesced */
		if (write_index != 0U) {
			drtm_mem_region_t *previous = &map->region[write_index - 1U];
			uint64_t previous_pages =
				(previous->region_size_type & page_count_mask) >>
				ARM_DRTM_REGION_SIZE_TYPE_4K_PAGE_NUM_SHIFT;
			uint64_t current_pages =
				(current->region_size_type & page_count_mask) >>
				ARM_DRTM_REGION_SIZE_TYPE_4K_PAGE_NUM_SHIFT;

			/* Can be coalesced if the types match, and the regions are contiguous.
			 * Checking for overflows before comparing. */
			if ((previous_pages <=
			     (UINT64_MAX - previous->region_address) /
			     PAGE_SIZE_4KB) &&
			    (previous->region_address +
			     (previous_pages * PAGE_SIZE_4KB) ==
			     current->region_address) &&
			    ((previous->region_size_type & ~page_count_mask) ==
			     (current->region_size_type & ~page_count_mask)) &&
			    (current_pages <=
			     ARM_DRTM_REGION_SIZE_TYPE_4K_PAGE_NUM_MASK -
			     previous_pages)) {
				ARM_DRTM_REGION_SIZE_TYPE_SET_4K_PAGE_NUM(
					previous->region_size_type,
					previous_pages + current_pages);

				continue;
			}
		}

		if (write_index != read_index) {
			map->region[write_index] = *current;
		}
		write_index++;
	}

	map->num_regions = write_index;
}

drtm_memory_region_descriptor_table_t *drtm_build_address_map(void)
{
	/* Set up pointer to DRTM memory map. */
	drtm_memory_region_descriptor_table_t *map =
		(drtm_memory_region_descriptor_table_t *)drtm_address_map;

	/* Get the platform memory map. */
	const mmap_region_t *mmap = plat_get_addr_mmap();
	unsigned int i;

	/* Set up header for address map structure. */
	map->revision = DRTM_ADDRESS_MAP_REVISION;
	map->reserved = 0x0000;

	/* Iterate through mmap and generate DRTM address map. */
	for (i = 0U; mmap[i].base_pa != 0UL; i++) {
		/* Set PA of region. */
		map->region[i].region_address = mmap[i].base_pa;

		/* Set size of region (in 4kb chunks). */
		map->region[i].region_size_type = 0;
		ARM_DRTM_REGION_SIZE_TYPE_SET_4K_PAGE_NUM(
			map->region[i].region_size_type,
			mmap[i].size / PAGE_SIZE_4KB);

		/* Set type and cacheability. */
		switch (MT_TYPE(mmap[i].attr)) {
		case MT_DEVICE:
			ARM_DRTM_REGION_SIZE_TYPE_SET_REGION_TYPE(
				map->region[i].region_size_type,
				ARM_DRTM_REGION_SIZE_TYPE_REGION_TYPE_DEVICE);
			break;
		case MT_NON_CACHEABLE:
			ARM_DRTM_REGION_SIZE_TYPE_SET_REGION_TYPE(
				map->region[i].region_size_type,
				ARM_DRTM_REGION_SIZE_TYPE_REGION_TYPE_NCAR);
			ARM_DRTM_REGION_SIZE_TYPE_SET_CACHEABILITY(
				map->region[i].region_size_type,
				ARM_DRTM_REGION_SIZE_TYPE_CACHEABILITY_NC);
			break;
		case MT_MEMORY:
			ARM_DRTM_REGION_SIZE_TYPE_SET_REGION_TYPE(
				map->region[i].region_size_type,
				ARM_DRTM_REGION_SIZE_TYPE_REGION_TYPE_NORMAL);
			break;
		default:
			return NULL;
		}
	}

	map->num_regions = i;

	qsort(map->region, map->num_regions, sizeof(drtm_mem_region_t),
	     compare_regions);

	/* Coalesce regions to satisfy DRTM requirement R314120. */
	coalesce_regions(map);

	/* Store total size of address map. */
	drtm_address_map_size = sizeof(drtm_memory_region_descriptor_table_t);
	drtm_address_map_size +=
		(map->num_regions * sizeof(drtm_mem_region_t));

	return map;
}

uint64_t drtm_get_address_map_size(void)
{
	return drtm_address_map_size;
}
