/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef IMX952_SCMI_DEF_H
#define IMX952_SCMI_DEF_H

#define IMR_NUM					(13)

#define IMX9_SCMI_CPU_A55C0			2U
#define IMX9_SCMI_CPU_A55C1			3U
#define IMX9_SCMI_CPU_A55C2			4U
#define IMX9_SCMI_CPU_A55C3			5U
#define IMX9_SCMI_CPU_A55P			6U

#define SCMI_PWR_MIX_SLICE_IDX_ANA		0U
#define SCMI_PWR_MIX_SLICE_IDX_AON		1U
#define SCMI_PWR_MIX_SLICE_IDX_BBSM		2U
#define SCMI_PWR_MIX_SLICE_IDX_CAMERA		3U
#define SCMI_PWR_MIX_SLICE_IDX_CCMSRCGPC	4U
#define SCMI_PWR_MIX_SLICE_IDX_A55C0		5U
#define SCMI_PWR_MIX_SLICE_IDX_A55C1		6U
#define SCMI_PWR_MIX_SLICE_IDX_A55C2		7U
#define SCMI_PWR_MIX_SLICE_IDX_A55C3		8U
#define SCMI_PWR_MIX_SLICE_IDX_A55P		9U
#define SCMI_PWR_MIX_SLICE_IDX_DDR		10U
#define SCMI_PWR_MIX_SLICE_IDX_DISPLAY		11U
#define SCMI_PWR_MIX_SLICE_IDX_GPU		12U
#define SCMI_PWR_MIX_SLICE_IDX_HSIO_TOP		13U
#define SCMI_PWR_MIX_SLICE_IDX_HSIO_WAON	14U
#define SCMI_PWR_MIX_SLICE_IDX_M7		15U
#define SCMI_PWR_MIX_SLICE_IDX_NETC		16U
#define SCMI_PWR_MIX_SLICE_IDX_NOC		17U
#define SCMI_PWR_MIX_SLICE_IDX_NPU		18U
#define SCMI_PWR_MIX_SLICE_IDX_VPU		19U
#define SCMI_PWR_MIX_SLICE_IDX_WAKEUP		20U

#define SCMI_PWR_MEM_SLICE_IDX_AON		0U
#define SCMI_PWR_MEM_SLICE_IDX_CAMERA		1U
#define SCMI_PWR_MEM_SLICE_IDX_A55C0		2U
#define SCMI_PWR_MEM_SLICE_IDX_A55C1		3U
#define SCMI_PWR_MEM_SLICE_IDX_A55C2		4U
#define SCMI_PWR_MEM_SLICE_IDX_A55C3		5U
#define SCMI_PWR_MEM_SLICE_IDX_A55P		6U
#define SCMI_PWR_MEM_SLICE_IDX_A55L3		7U
#define SCMI_PWR_MEM_SLICE_IDX_DDR		8U
#define SCMI_PWR_MEM_SLICE_IDX_DISPLAY		9U
#define SCMI_PWR_MEM_SLICE_IDX_GPU		10U
#define SCMI_PWR_MEM_SLICE_IDX_HSIO		11U
#define SCMI_PWR_MEM_SLICE_IDX_M7		12U
#define SCMI_PWR_MEM_SLICE_IDX_NETC		13U
#define SCMI_PWR_MEM_SLICE_IDX_NOC_OCRAM	14U
#define SCMI_PWR_MEM_SLICE_IDX_NOC2		15U
#define SCMI_PWR_MEM_SLICE_IDX_NPU		16U
#define SCMI_PWR_MEM_SLICE_IDX_VPU		17U
#define SCMI_PWR_MEM_SLICE_IDX_WAKEUP		18U

/* Peripheral LPI index */
#define CPU_PER_LPI_IDX_GPIO1			0U
#define CPU_PER_LPI_IDX_GPIO2			1U
#define CPU_PER_LPI_IDX_GPIO3			2U
#define CPU_PER_LPI_IDX_GPIO4			3U
#define CPU_PER_LPI_IDX_GPIO5			4U
#define CPU_PER_LPI_IDX_CAN1			5U
#define CPU_PER_LPI_IDX_CAN2			6U
#define CPU_PER_LPI_IDX_CAN3			7U
#define CPU_PER_LPI_IDX_LPUART1		8U
#define CPU_PER_LPI_IDX_LPUART2		9U
#define CPU_PER_LPI_IDX_LPUART3		10U
#define CPU_PER_LPI_IDX_LPUART4		11U
#define CPU_PER_LPI_IDX_LPUART5		12U
#define CPU_PER_LPI_IDX_LPUART6		13U
#define CPU_PER_LPI_IDX_LPUART7		14U
#define CPU_PER_LPI_IDX_LPUART8		15U
#define CPU_PER_LPI_IDX_WDOG3			16U
#define CPU_PER_LPI_IDX_WDOG4			17U
#define CPU_PER_LPI_IDX_WDOG5			18U

#define DEBUG_WAKEUP_MASK			BIT(1)
#define EVENT_WAKEUP_MASK			BIT(0)

#endif /* IMX952_SCMI_DEF_H */
