/*
 * Copyright (c) 2015-2018, ARM Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef IMX8_IOMUX_H
#define IMX8_IOMUX_H

#define PADRING_IFMUX_EN_SHIFT		31
#define PADRING_IFMUX_EN_MASK		(1 << PADRING_IFMUX_EN_SHIFT)
#define PADRING_GP_EN_SHIFT		30
#define PADRING_GP_EN_MASK		(1 << PADRING_GP_EN_SHIFT)
#define PADRING_IFMUX_SHIFT		27
#define PADRING_IFMUX_MASK		(0x7 << PADRING_IFMUX_SHIFT)
#define PADRING_CONFIG_SHIFT		25
#define PADRING_CONFIG_MASK		(0x3 << PADRING_CONFIG_SHIFT)
#define PADRING_LPCONFIG_SHIFT		23
#define PADRING_LPCONFIG_MASK		(0x3 << PADRING_LPCONFIG_SHIFT)
#define PADRING_PULL_SHIFT		5
#define PADRING_PULL_MASK		(0x3 << PADRING_PULL_SHIFT)
#define PADRING_DSE_SHIFT		0
#define PADRING_DSE_MASK		(0x7 << PADRING_DSE_SHIFT)

#endif /* IMX8_IOMUX_H */
