/*
 * Copyright (c) 2025-2026, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef INITIAL_ATTESTATION_H
#define INITIAL_ATTESTATION_H

#include <stddef.h>
#include <stdint.h>

#include <psa/error.h>

/* RSE Initial Attestation message types that distinguish its services. */
#define RSE_INITIAL_ATTESTATION_GET_TOKEN		1001U
#define RSE_INITIAL_ATTESTATION_GET_TOKEN_SIZE		1002U

/**
 * The allowed size of input challenge in bytes: 32, 48, 64
 * Challenge can be a nonce from server
 * or the hash of some combined data : nonce + attested data by caller.
 */
#define PSA_INITIAL_ATTEST_CHALLENGE_SIZE_32		32U
#define PSA_INITIAL_ATTEST_CHALLENGE_SIZE_48		48U
#define PSA_INITIAL_ATTEST_CHALLENGE_SIZE_64		64U

/**
 * Get an initial attestation token from RSE.
 *
 * The token contains claims describing the platform boot state and security
 * lifecycle, and is generated by RSE using the caller-provided challenge.
 * The challenge is included in the token to bind the token to the attestation
 * request.
 *
 * challenge_buf       Pointer to the challenge buffer.
 * challenge_size      Size of the challenge, in bytes.
 * token_buf           Pointer to the buffer where the initial attestation token
 *                     will be stored.
 * token_buf_size      Size of allocated buffer for the token, in bytes.
 * token_size          Size of the token that has been returned, in bytes.
 *
 * Returns error code as specified in psa_status_t.
 *
 * Notes:
 *   - token_size must not be NULL.
 *   - On PSA_OPERATION_INCOMPLETE, token_size is set to 0.
 */
psa_status_t rse_initial_attest_get_token(const uint8_t *challenge_buf,
					  size_t challenge_size,
					  uint8_t *token_buf,
					  size_t token_buf_size,
					  size_t *token_size);

/**
 * Get the expected size of an initial attestation token.
 *
 * This API returns the token size RSE expects to generate for a challenge with
 * the supplied length. Callers can use it to allocate a token buffer before
 * calling rse_initial_attest_get_token().
 *
 * challenge_size      Size of the challenge, in bytes.
 * token_size          Expected token size, in bytes.
 *
 * Returns error code as specified in psa_status_t.
 *
 * Notes:
 *   - token_size must not be NULL.
 */
psa_status_t rse_initial_attest_get_token_size(size_t challenge_size,
					       size_t *token_size);

#endif /* INITIAL_ATTESTATION_H */
