/*
 * Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <drivers/qti/pdc/pdc_internal.h>
#include <lib/utils_def.h>

/* GPIO mapping for lemans (qcs9075) APSS */
struct pdc_gpio_mapping g_pdc_gpio_mapping[] = {
	/* { trig_config,                  subsystem_irq } */
	/* Mux 0 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 552 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 553 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 554 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 555 },

	/* Mux 4 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 556 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 557 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 558 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 559 },

	/* Mux 8 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 560 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 561 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 562 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 563 },

	/* Mux 12 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 564 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 565 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 566 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 567 },

	/* Mux 16 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 568 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 569 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 570 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 571 },

	/* Mux 20 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 572 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 573 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 574 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 575 },

	/* Mux 24 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 576 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 577 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 578 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 579 },

	/* Mux 28 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 580 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 581 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 582 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 583 },

	/* Mux 32 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 584 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 585 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 586 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 587 },

	/* Mux 36 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 588 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 589 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 590 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 591 },

	/* Mux 40 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 592 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 593 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 594 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 595 },

	/* Mux 44 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 596 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 597 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 598 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 599 },

	/* Mux 48 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 600 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 601 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 602 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 603 },

	/* Mux 52 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 604 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 605 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 641 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 642 },

	/* Mux 56 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 643 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 644 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 645 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 646 },

	/* Mux 60 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 647 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 648 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 649 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 650 },

	/* Mux 64 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 651 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 652 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 653 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 654 },

	/* Mux 68 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 655 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 656 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 657 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 658 },

	/* Mux 72 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 659 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 660 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 661 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 662 },

	/* Mux 76 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 663 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 664 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 665 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 666 },

	/* Mux 80 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 667 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 668 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 669 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 670 },

	/* Mux 84 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 671 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 },  95 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 748 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 749 },

	/* Mux 88 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 750 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 751 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 752 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 753 },

	/* Mux 92 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 754 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 755 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 756 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 757 },

	/* Mux 96 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 758 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, 759 },
};

const uint32_t g_pdc_gpio_mapping_size = ARRAY_SIZE(g_pdc_gpio_mapping);
