/*
 * Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <stddef.h>

#include <drivers/qti/pdc/pdc_internal.h>
#include <lib/utils_def.h>

/* GPIO MUX mapping for lemans (qcs9075) APSS */
struct pdc_gpio_mapping g_pdc_gpio_mapping[] = {
	/* { trig_config,                  gpio_tbl_ptr, subsystem_irq } */
	/* Mux 0 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 552 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 553 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 554 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 555 },

	/* Mux 4 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 556 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 557 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 558 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 559 },

	/* Mux 8 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 560 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 561 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 562 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 563 },

	/* Mux 12 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 564 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 565 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 566 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 567 },

	/* Mux 16 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 568 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 569 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 570 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 571 },

	/* Mux 20 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 572 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 573 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 574 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 575 },

	/* Mux 24 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 576 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 577 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 578 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 579 },

	/* Mux 28 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 580 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 581 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 582 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 583 },

	/* Mux 32 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 584 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 585 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 586 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 587 },

	/* Mux 36 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 588 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 589 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 590 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 591 },

	/* Mux 40 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 592 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 593 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 594 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 595 },

	/* Mux 44 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 596 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 597 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 598 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 599 },

	/* Mux 48 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 600 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 601 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 602 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 603 },

	/* Mux 52 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 604 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 605 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 641 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 642 },

	/* Mux 56 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 643 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 644 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 645 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 646 },

	/* Mux 60 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 647 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 648 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 649 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 650 },

	/* Mux 64 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 651 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 652 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 653 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 654 },

	/* Mux 68 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 655 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 656 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 657 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 658 },

	/* Mux 72 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 659 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 660 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 661 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 662 },

	/* Mux 76 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 663 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 664 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 665 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 666 },

	/* Mux 80 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 667 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 668 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 669 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 670 },

	/* Mux 84 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 671 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL,  95 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 748 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 749 },

	/* Mux 88 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 750 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 751 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 752 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 753 },

	/* Mux 92 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 754 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 755 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 756 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 757 },

	/* Mux 96 */
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 758 },
	{ { TRIGGER_RISING_EDGE, PDC_DRV2 }, NULL, 759 },
};

const uint32_t g_pdc_gpio_mapping_size = ARRAY_SIZE(g_pdc_gpio_mapping);
