/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SMEM_TYPE_H
#define SMEM_TYPE_H

#include <stdint.h>

#define SMEM_VERSION_ID	0x000C0001

#define SMEM_MAJOR_VERSION_MASK	0xFFFF0000

#define SMEM_NUM_SMD_CHANNELS	64
#define SMEM_NUM_SMP2P_EDGES	8

/*
 * Types of memory that can be requested via smem_alloc.
 *
 * All of these types of memory have corresponding buffers allocated in
 * smem_data_decl. If a buffer is added to smem_data_decl, add a
 * corresponding entry to this list.
 *
 * SMEM_VERSION_FIRST and SMEM_VERSION_LAST are the first and last
 * boundaries for external version checking via the smem_version_set routine.
 * To set up versioning for a shared item, add an entry between
 * SMEM_VERSION_FIRST and SMEM_VERSION_LAST and update the SMEM version in
 * smem_version.h.
 *
 * SMEM_VERSION_LAST need not be the last item in the enum.
 */
enum smem_mem_type {
	SMEM_MEM_FIRST,
	SMEM_RESERVED_PROC_COMM = SMEM_MEM_FIRST,
	SMEM_FIRST_FIXED_BUFFER = SMEM_RESERVED_PROC_COMM,
	SMEM_HEAP_INFO,
	SMEM_ALLOCATION_TABLE,
	SMEM_VERSION_INFO,
	SMEM_HW_RESET_DETECT,
	SMEM_RESERVED_AARM_WARM_BOOT,
	SMEM_DIAG_ERR_MESSAGE,
	SMEM_SPINLOCK_ARRAY,
	SMEM_MEMORY_BARRIER_LOCATION,
	SMEM_LAST_FIXED_BUFFER = SMEM_MEMORY_BARRIER_LOCATION,
	SMEM_AARM_PARTITION_TABLE,
	SMEM_AARM_BAD_BLOCK_TABLE,
	SMEM_ERR_CRASH_LOG_ADSP,
	SMEM_BOOT_BOARD_INFO,
	SMEM_CHANNEL_ALLOC_TBL,
	SMEM_SMD_BASE_ID,
	SMEM_SMEM_LOG_IDX = SMEM_SMD_BASE_ID + SMEM_NUM_SMD_CHANNELS,
	SMEM_SMEM_LOG_EVENTS,
	SMEM_RESERVED_SMEM_STATIC_LOG_IDX,
	SMEM_XBL_LOADER_CORE_INFO = SMEM_RESERVED_SMEM_STATIC_LOG_IDX,
	SMEM_RESERVED_SMEM_STATIC_LOG_EVENTS,
	SMEM_CHARGER_BATTERY_INFO = SMEM_RESERVED_SMEM_STATIC_LOG_EVENTS,
	SMEM_RESERVED_SMEM_SLOW_CLOCK_SYNC,
	SMEM_WLAN_CONFIG = SMEM_RESERVED_SMEM_SLOW_CLOCK_SYNC,
	SMEM_RESERVED_SMEM_SLOW_CLOCK_VALUE,
	SMEM_RESERVED_BIO_LED_BUF,
	SMEM_SMSM_SHARED_STATE,
	SMEM_RESERVED_SMSM_INT_INFO,
	SMEM_RESERVED_SMSM_SLEEP_DELAY,
	SMEM_RESERVED_SMSM_LIMIT_SLEEP,
	SMEM_RESERVED_SLEEP_POWER_COLLAPSE_DISABLED,
	SMEM_RESERVED_KEYPAD_KEYS_PRESSED,
	SMEM_RESERVED_KEYPAD_STATE_UPDATED,
	SMEM_RESERVED_KEYPAD_STATE_IDX,
	SMEM_RESERVED_GPIO_INT,
	SMEM_ID_SMP2P_BASE_CDSP,
	SMEM_RESERVED_SMD_PROFILES =
		SMEM_ID_SMP2P_BASE_CDSP + SMEM_NUM_SMP2P_EDGES,
	SMEM_RESERVED_TSSC_BUSY,
	SMEM_RESERVED_HS_SUSPEND_FILTER_INFO,
	SMEM_RESERVED_BATT_INFO,
	SMEM_RESERVED_APPS_BOOT_MODE,
	SMEM_VERSION_FIRST,
	SMEM_VERSION_SMD = SMEM_VERSION_FIRST,
	SMEM_VERSION_SMD_BRIDGE,
	SMEM_VERSION_SMSM,
	SMEM_VERSION_SMD_NWAY_LOOP,
	SMEM_VERSION_LAST = SMEM_VERSION_FIRST + 24,
	SMEM_RESERVED_OSS_RRCASN1_BUF1,
	SMEM_RESERVED_OSS_RRCASN1_BUF2,
	SMEM_ID_VENDOR0,
	SMEM_ID_VENDOR1,
	SMEM_ID_VENDOR2,
	SMEM_HW_SW_BUILD_ID,
	SMEM_RESERVED_SMD_BLOCK_PORT_BASE_ID,
	SMEM_RESERVED_SMD_BLOCK_PORT_PROC0_HEAP =
		SMEM_RESERVED_SMD_BLOCK_PORT_BASE_ID + SMEM_NUM_SMD_CHANNELS,
	SMEM_RESERVED_SMD_BLOCK_PORT_PROC1_HEAP =
		SMEM_RESERVED_SMD_BLOCK_PORT_PROC0_HEAP + SMEM_NUM_SMD_CHANNELS,
	SMEM_I2C_MUTEX =
		SMEM_RESERVED_SMD_BLOCK_PORT_PROC1_HEAP + SMEM_NUM_SMD_CHANNELS,
	SMEM_SCLK_CONVERSION,
	SMEM_RESERVED_SMD_SMSM_INTR_MUX,
	SMEM_SMSM_CPU_INTR_MASK,
	SMEM_RESERVED_APPS_DEM_SLAVE_DATA,
	SMEM_RESERVED_QDSP6_DEM_SLAVE_DATA,
	SMEM_VSENSE_DATA,
	SMEM_RESERVED_CLKREGIM_SOURCES,
	SMEM_SMD_FIFO_BASE_ID,
	SMEM_USABLE_RAM_PARTITION_TABLE =
		SMEM_SMD_FIFO_BASE_ID + SMEM_NUM_SMD_CHANNELS,
	SMEM_POWER_ON_STATUS_INFO,
	SMEM_DAL_AREA,
	SMEM_SMEM_LOG_POWER_IDX,
	SMEM_SMEM_LOG_POWER_WRAP,
	SMEM_SMEM_LOG_POWER_EVENTS,
	SMEM_ERR_CRASH_LOG,
	SMEM_ERR_F3_TRACE_LOG,
	SMEM_SMD_BRIDGE_ALLOC_TABLE,
	SMEM_SMD_FEATURE_SET,
	SMEM_RESERVED_SD_IMG_UPGRADE_STATUS,
	SMEM_SEFS_INFO,
	SMEM_RESERVED_RESET_LOG,
	SMEM_RESERVED_RESET_LOG_SYMBOLS,
	SMEM_MODEM_SW_BUILD_ID,
	SMEM_SMEM_LOG_MPROC_WRAP,
	SMEM_RESERVED_BOOT_INFO_FOR_APPS,
	SMEM_SMSM_SIZE_INFO,
	SMEM_SMD_LOOPBACK_REGISTER,
	SMEM_SSR_REASON_MSS0,
	SMEM_SSR_REASON_WCNSS0,
	SMEM_SSR_REASON_LPASS0,
	SMEM_SSR_REASON_DSPS0,
	SMEM_SSR_REASON_VCODEC0,
	SMEM_VOICE,
	SMEM_ID_SMP2P_BASE_APPS, /* = 427 */
	SMEM_ID_SMP2P_BASE_MODEM =
		SMEM_ID_SMP2P_BASE_APPS + SMEM_NUM_SMP2P_EDGES, /* = 435 */
	SMEM_ID_SMP2P_BASE_ADSP =
		SMEM_ID_SMP2P_BASE_MODEM + SMEM_NUM_SMP2P_EDGES, /* = 443 */
	SMEM_ID_SMP2P_BASE_WCN =
		SMEM_ID_SMP2P_BASE_ADSP + SMEM_NUM_SMP2P_EDGES, /* = 451 */
	SMEM_ID_SMP2P_BASE_RPM =
		SMEM_ID_SMP2P_BASE_WCN + SMEM_NUM_SMP2P_EDGES, /* = 459 */
	SMEM_FLASH_DEVICE_INFO =
		SMEM_ID_SMP2P_BASE_RPM + SMEM_NUM_SMP2P_EDGES, /* = 467 */
	SMEM_BAM_PIPE_MEMORY, /* = 468 */
	SMEM_IMAGE_VERSION_TABLE, /* = 469 */
	SMEM_LC_DEBUGGER, /* = 470 */
	SMEM_FLASH_NAND_DEV_INFO, /* = 471 */
	SMEM_A2_BAM_DESCRIPTOR_FIFO, /* = 472 */
	SMEM_CPR_CONFIG, /* = 473 */
	SMEM_CLOCK_INFO, /* = 474 */
	SMEM_IPC_INFO, /* = 475 */
	SMEM_RF_EEPROM_DATA, /* = 476 */
	SMEM_COEX_MDM_WCN, /* = 477 */
	SMEM_GLINK_NATIVE_XPORT_DESCRIPTOR, /* = 478 */
	SMEM_GLINK_NATIVE_XPORT_FIFO_0, /* = 479 */
	SMEM_GLINK_NATIVE_XPORT_FIFO_1, /* = 480 */
	SMEM_ID_SMP2P_BASE_SSC = 481, /* = 481 */
	SMEM_ID_SMP2P_BASE_TZ = SMEM_ID_SMP2P_BASE_SSC + /* = 489 */
				SMEM_NUM_SMP2P_EDGES,
	SMEM_IPA_FILTER_TABLE = SMEM_ID_SMP2P_BASE_TZ + /* = 497 */
				SMEM_NUM_SMP2P_EDGES,
	SMEM_MEM_LAST = SMEM_IPA_FILTER_TABLE,
	SMEM_INVALID /* = 498 */
};

/*
 * SMEM Host ID
 * <chiplet:3><pd_num:3><proc_num:4><proc_id:6>
 */
#define SMEM_HOST_ID_PROC_ID_BMSK	0x3F
#define SMEM_HOST_ID_PROC_ID_SHFT	0x0
#define SMEM_HOST_ID_PROC_NUM_BMSK	0xF
#define SMEM_HOST_ID_PROC_NUM_SHFT	0x6
#define SMEM_HOST_ID_PD_NUM_BMSK	0x7
#define SMEM_HOST_ID_PD_NUM_SHFT	0xA
#define SMEM_HOST_ID_CHIPLET_BMSK	0x7
#define SMEM_HOST_ID_CHIPLET_SHFT	0xD

#define SMEM_HOST_ID(proc_id, proc_num, pd_num, chiplet)             \
	((uint16_t)((((proc_id) & SMEM_HOST_ID_PROC_ID_BMSK)         \
			   << SMEM_HOST_ID_PROC_ID_SHFT) |           \
			  (((proc_num) & SMEM_HOST_ID_PROC_NUM_BMSK) \
			   << SMEM_HOST_ID_PROC_NUM_SHFT) |          \
			  (((pd_num) & SMEM_HOST_ID_PD_NUM_BMSK)     \
			   << SMEM_HOST_ID_PD_NUM_SHFT) |            \
			  (((chiplet) & SMEM_HOST_ID_CHIPLET_BMSK)   \
			   << SMEM_HOST_ID_CHIPLET_SHFT)))

/*
 * SMEM Processor/Subsystem ID for this processor.
 */
#define SMEM_PROC_TZ	7 /* TZ processor */

/*
 * SMEM host for this processor.
 */
#define SMEM_TZ		SMEM_HOST_ID(SMEM_PROC_TZ, 0, 0, 0) /*< TZ processor */

/* Common host */
#define SMEM_COMMON_HOST	((uint16_t)0xFFFE)
/* Invalid processor */
#define SMEM_INVALID_HOST	((uint16_t)0xFFFF)

#endif /* SMEM_TYPE_H */
