/*
 * Copyright (c) 2026, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef FIRME_IDE_KM_H
#define FIRME_IDE_KM_H

#include <services/firme/firme_abi.h>

#define FIRME_IDE_KEY_MGMT_VERSION_MAJOR	U(1)
#define FIRME_IDE_KEY_MGMT_VERSION_MINOR	U(0)

#define FIRME_IDE_KM_FNUM_KEYSET_PROG		U(0x3)
#define FIRME_IDE_KM_FNUM_KEYSET_GO		U(0x4)
#define FIRME_IDE_KM_FNUM_KEYSET_STOP		U(0x5)
#define FIRME_IDE_KM_FNUM_KEYSET_POLL		U(0x6)

#define FIRME_IDE_KEYSET_PROG_FID		FIRME_FID(FIRME_IDE_KM_FNUM_KEYSET_PROG)
#define FIRME_IDE_KEYSET_GO_FID			FIRME_FID(FIRME_IDE_KM_FNUM_KEYSET_GO)
#define FIRME_IDE_KEYSET_STOP_FID		FIRME_FID(FIRME_IDE_KM_FNUM_KEYSET_STOP)
#define FIRME_IDE_KEYSET_POLL_FID		FIRME_FID(FIRME_IDE_KM_FNUM_KEYSET_POLL)

#endif /* FIRME_IDE_KM_H */
