/*
 * Copyright (c) 2026, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef FIRME_ATTESTATION_H
#define FIRME_ATTESTATION_H

#include <services/firme/firme_abi.h>

#define FIRME_ATTESTATION_VERSION_MAJOR		U(0)
#define FIRME_ATTESTATION_VERSION_MINOR		U(0)

#define FIRME_ATTEST_FNUM_PAT_GET		U(0x8)
#define FIRME_ATTEST_FNUM_RAK_GET		U(0x9)
#define FIRME_ATTEST_FNUM_RAT_SIGN		U(0xA)
#define FIRME_ATTEST_FNUM_PAT_EXT_CLAIMS_STAGE	U(0xB)
#define FIRME_ATTEST_FNUM_PAT_EXT_CLAIMS_CLEAR	U(0xC)
#define FIRME_ATTEST_FNUM_PAT_EXT_CLAIMS_FINALISE U(0xD)

#define FIRME_ATTEST_PAT_GET_FID FIRME_FID(FIRME_ATTEST_FNUM_PAT_GET)
#define FIRME_ATTEST_RAK_GET_FID FIRME_FID(FIRME_ATTEST_FNUM_RAK_GET)
#define FIRME_ATTEST_RAT_SIGN_FID FIRME_FID(FIRME_ATTEST_FNUM_RAT_SIGN)
#define FIRME_ATTEST_PAT_EXT_CLAIMS_STAGE_FID	\
	FIRME_FID(FIRME_ATTEST_FNUM_PAT_EXT_CLAIMS_STAGE)
#define FIRME_ATTEST_PAT_EXT_CLAIMS_CLEAR_FID	\
	FIRME_FID(FIRME_ATTEST_FNUM_PAT_EXT_CLAIMS_CLEAR)
#define FIRME_ATTEST_PAT_EXT_CLAIMS_FINALISE_FID	\
	FIRME_FID(FIRME_ATTEST_FNUM_PAT_EXT_CLAIMS_FINALISE)

#endif /* FIRME_ATTESTATION_H */
