/*
 * Copyright (c) 2019-2026, Intel Corporation. All rights reserved.
 * Copyright (c) 2024-2026, Altera Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef AGILEX72_SOCFPGA_SYSTEM_MANAGER_H
#define AGILEX72_SOCFPGA_SYSTEM_MANAGER_H

#include "socfpga_plat_def.h"

/* System Manager Register Map */

#define SOCFPGA_SYSMGR_EMAC_0							0x44 /* TSN_0 */
#define SOCFPGA_SYSMGR_EMAC_1							0x48 /* TSN_1 */
#define SOCFPGA_SYSMGR_EMAC_2							0x4C /* TSN_2 */
#define SOCFPGA_SYSMGR_FPGA_BRIDGE_CTRL					0x5C
#define SOCFPGA_SYSMGR_FPGA2SOC_CTRL					0xD8
#define SOCFPGA_SYSMGR_F2S_BRIDGE_CTRL					0x14C
#define SOCFPGA_SYSMGR_SDM_TBU_STREAM_CTRL_REG_1_SDM			0x184
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_CTRL_REG_2_USB2			0x188
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_CTRL_REG_2_USB3			0x18C
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_CTRL_REG_2_SDMMC			0x190
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_CTRL_REG_2_NAND			0x194
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_CTRL_REG_2_ETR			0x198
#define SOCFPGA_SYSMGR_TSN_TBU_STREAM_CTRL_REG_3_TSN0			0x19C
#define SOCFPGA_SYSMGR_TSN_TBU_STREAM_CTRL_REG_3_TSN1			0x1A0
#define SOCFPGA_SYSMGR_TSN_TBU_STREAM_CTRL_REG_3_TSN2			0x1A4
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_ID_AX_REG_2_USB2			0x1B4
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_ID_AX_REG_2_USB3			0x1B8
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_ID_AX_REG_2_SDMMC			0x1BC
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_ID_AX_REG_2_NAND			0x1C0
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_ID_AX_REG_2_ETR			0x1C4
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_ID_AX_REG_2_TSN0			0x1C8
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_ID_AX_REG_2_TSN1			0x1CC
#define SOCFPGA_SYSMGR_IO_TBU_STREAM_ID_AX_REG_2_TSN2			0x1D0


/* NOC configuration value */


#define SOCFPGA_SYSMGR_SILICONID_1						0x20
#define SOCFPGA_SYSMGR_SILICONID_2						0x24
#define SOCFPGA_SYSMGR_MPU_STATUS						0x20

#define SOCFPGA_SYSMGR_ECC_INTMASK_VALUE				0x00
#define SOCFPGA_SYSMGR_ECC_INTMASK_SET					0x04
#define SOCFPGA_SYSMGR_ECC_INTMASK_CLR					0x08
#define SOCFPGA_SYSMGR_ECC_INTMASK_SERR					0x0C
#define SOCFPGA_SYSMGR_ECC_INTMASK_DERR					0x10

#define SOCFPGA_SYSMGR_FPGAINTF_EN_1				SOCFPGA_HSP_SYSMGR_FPGAINTF_EN_1
#define SOCFPGA_SYSMGR_FPGAINTF_EN_2				SOCFPGA_HSP_SYSMGR_FPGAINTF_EN_2
#define SOCFPGA_SYSMGR_FPGAINTF_EN_3				SOCFPGA_HSP_SYSMGR_FPGAINTF_EN_3
#define SOCFPGA_HSP_SYSMGR_FPGAINTF_EN_1						0x38
#define SOCFPGA_HSP_SYSMGR_FPGAINTF_EN_2						0x3C
#define SOCFPGA_HSP_SYSMGR_FPGAINTF_EN_3						0x78

/* HSP sysmgr BOOT_SCRATCH_COLD layout (SOC64-compatible, offset base 0x680) */
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_0					0x680
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_1					0x684
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_2					0x688
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_3					0x68C
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_4					0x690
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_5					0x694
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_6					0x698
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_7					0x69C
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_8					0x6A0
#define SOCFPGA_HSP_SYSMGR_BOOT_SCRATCH_COLD_9					0x6A4

#define SOCFPGA_SYSMGR_DMAC0_L3_MASTER				SOCFPGA_LSP_SYSMGR_DMAC0_L3_MASTER
#define SOCFPGA_SYSMGR_ETR_L3_MASTER				SOCFPGA_LSP_SYSMGR_ETR_L3_MASTER
#define SOCFPGA_SYSMGR_DMAC1_L3_MASTER				SOCFPGA_LSP_SYSMGR_DMAC1_L3_MASTER
#define SOCFPGA_LSP_SYSMGR_DMAC0_L3_MASTER						0x44
#define SOCFPGA_LSP_SYSMGR_ETR_L3_MASTER						0x48
#define SOCFPGA_LSP_SYSMGR_DMAC1_L3_MASTER						0x4C

#define SOCFPGA_SYSMGR_SEC_CTRL_SLT				SOCFPGA_LSP_SYSMGR_SEC_CTRL_SLT
#define SOCFPGA_LSP_SYSMGR_SEC_CTRL_SLT							0x50

#define SOCFPGA_SYSMGR_OSC_TRIM						SOCFPGA_LSP_SYSMGR_OSC_TRIM
#define SOCFPGA_LSP_SYSMGR_OSC_TRIM								0x84

#define SOCFPGA_SYSMGR_DMAC0_CTRL_STATUS_REG		SOCFPGA_LSP_SYSMGR_DMAC0_CTRL_STATUS_REG
#define SOCFPGA_LSP_SYSMGR_DMAC0_CTRL_STATUS_REG				0x58

#define SOCFPGA_SYSMGR_DMAC1_CTRL_STATUS_REG		SOCFPGA_LSP_SYSMGR_DMAC1_CTRL_STATUS_REG
#define SOCFPGA_LSP_SYSMGR_DMAC1_CTRL_STATUS_REG				0x5C

#define SOCFPGA_SYSMGR_NOC_TIMEOUT								0x7C
#define SOCFPGA_SYSMGR_NOC_IDLESTATUS							0x80

#define SOCFPGA_SYSMGR_FPGA_CFG									0x6C

#define SOCFPGA_SYSMGR_GPO						0x70
#define SOCFPGA_SYSMGR_GPI						0x74

#define SOCFPGA_SYSMGR_DFI_INTF									0x78

#define SOCFPGA_SYSMGR_DMA_TBU_STREAM_CTRL_REG_0_DMA0 \
	SOCFPGA_LSP_SYSMGR_DMA_TBU_STREAM_CTRL_REG_5_DMA0
#define SOCFPGA_LSP_SYSMGR_DMA_TBU_STREAM_CTRL_REG_5_DMA0		0xD04
#define SOCFPGA_SYSMGR_DMA_TBU_STREAM_CTRL_REG_0_DMA1 \
	SOCFPGA_LSP_SYSMGR_DMA_TBU_STREAM_CTRL_REG_0_DMA1
#define SOCFPGA_LSP_SYSMGR_DMA_TBU_STREAM_CTRL_REG_0_DMA1		0xD10

#define SOCFPGA_SYSMGR_DMA_TBU_STREAM_ID_AX_REG_0_DMA0 \
	SOCFPGA_LSP_SYSMGR_DMA_TBU_STREAM_ID_AX_REG_0_DMA0
#define SOCFPGA_LSP_SYSMGR_DMA_TBU_STREAM_ID_AX_REG_0_DMA0		0xD08
#define SOCFPGA_SYSMGR_DMA_TBU_STREAM_ID_AX_REG_0_DMA1 \
	SOCFPGA_LSP_SYSMGR_DMA_TBU_STREAM_ID_AX_REG_0_DMA1
#define SOCFPGA_LSP_SYSMGR_DMA_TBU_STREAM_ID_AX_REG_0_DMA1		0xD14

#define SOCFPGA_SYSMGR_SDM_TBU_STREAM_ID_AX_REG_1_SDM \
	SOCFPGA_SYSMGR_SDM_TBU_STREAM_ID_AX_REG_3_SDM
#define SOCFPGA_SYSMGR_SDM_TBU_STREAM_ID_AX_REG_3_SDM			0x538

#define SOCFPGA_SYSMGR_USB3_MISC_CTRL_REG0				0x20
#define SOCFPGA_SYSMGR_USB3_MISC_CTRL_REG1				0x24

#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_0			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_0
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_1			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_1
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_2			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_2
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_3			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_3
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_4			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_4
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_5			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_5
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_6			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_6
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_7			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_7
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_8			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_8
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_COLD_9			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_9
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_0			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_0
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_1			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_1
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_2			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_2
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_3			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_3
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_4			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_4
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_5			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_5
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_6			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_6
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_7			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_7
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_8			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_8
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_WARM_9			SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_9

#define SOCFPGA_SYSMGR_MPFE_CONFIG					0x228
#define SOCFPGA_SYSMGR_MPFE_STATUS					0x22C

/* APU SYSMGR BOOTSCRACH POR */
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_0				0x600
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_1				0x604
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_2				0x608
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_3				0x60C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_4				0x610
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_5				0x614
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_6				0x618
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_7				0x61C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_8				0x620
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_9				0x624
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_10				0x628
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_11				0x62C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_12				0x630
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_13				0x634
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_14				0x638
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_15				0x63C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_16				0x640
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_17				0x644
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_18				0x648
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_19				0x64C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_20				0x650
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_21				0x654
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_22				0x658
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_23				0x65C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_24				0x660
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_25				0x664
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_26				0x668
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_27				0x66C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_28				0x670
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_29				0x674
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_30				0x678
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_31				0x67C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_32				0x680
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_33				0x684
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_34				0x688
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_35				0x68C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_36				0x690
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_37				0x694
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_38				0x698
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_39				0x69C
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_40				0x6A0
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_41				0x6A4
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_42				0x6A8
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_43				0x6AC
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_44				0x6B0
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_45				0x6B4
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_46				0x6B8
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_47				0x6BC
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_48				0x6C0
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_49				0x6C4
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_50				0x6C8
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_51				0x6CC
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_52				0x6D0
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_53				0x6D4
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_54				0x6D8
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_55				0x6DC
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_56				0x6E0
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_57				0x6E4
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_58				0x6E8
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_59				0x6EC
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_60				0x6F0
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_61				0x6F4
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_62				0x6F8
#define SOCFPGA_SYSMGR_BOOT_SCRATCH_POR_63				0x6FC

/* LSP SYSMGR BOOTSCRACH POR */
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_0			0xE00
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_1			0xE04
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_2			0xE08
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_3			0xE0C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_4			0xE10
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_5			0xE14
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_6			0xE18
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_7			0xE1C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_8			0xE20
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_9			0xE24
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_10			0xE28
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_11			0xE2C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_12			0xE30
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_13			0xE34
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_14			0xE38
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_15			0xE3C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_16			0xE40
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_17			0xE44
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_18			0xE48
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_19			0xE4C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_20			0xE50
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_21			0xE54
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_22			0xE58
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_23			0xE5C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_24			0xE60
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_25			0xE64
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_26			0xE68
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_27			0xE6C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_28			0xE70
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_29			0xE74
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_30			0xE78
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_31			0xE7C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_32			0xE80
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_33			0xE84
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_34			0xE88
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_35			0xE8C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_36			0xE90
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_37			0xE94
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_38			0xE98
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_39			0xE9C
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_40			0xEA0
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_41			0xEA4
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_42			0xEA8
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_43			0xEAC
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_44			0xEB0
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_45			0xEB4
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_46			0xEB8
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_47			0xEBC
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_48			0xEC0
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_49			0xEC4
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_50			0xEC8
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_51			0xECC
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_52			0xED0
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_53			0xED4
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_54			0xED8
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_55			0xEDC
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_56			0xEE0
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_57			0xEE4
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_58			0xEE8
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_59			0xEEC
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_60			0xEF0
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_61			0xEF4
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_62			0xEF8
#define SOCFPGA_LSP_SYSMGR_BOOT_SCRATCH_POR_63			0xEFC

#define SOCFPGA_SYSMGR_SDM_BE_AWADDR_REMAP				0x280
#define SOCFPGA_SYSMGR_SDM_BE_ARADDR_REMAP				0x284

/* QSPI ECC from SDM register */
#define SOCFPGA_ECC_QSPI_CTRL						0x08
#define SOCFPGA_ECC_QSPI_INITSTAT					0x0C
#define SOCFPGA_ECC_QSPI_ERRINTEN					0x10
#define SOCFPGA_ECC_QSPI_ERRINTENS					0x14
#define SOCFPGA_ECC_QSPI_ERRINTENR					0x18
#define SOCFPGA_ECC_QSPI_INTMODE					0x1C
#define SOCFPGA_ECC_QSPI_INTSTAT					0x20
#define SOCFPGA_ECC_QSPI_INTTEST					0x24
#define SOCFPGA_ECC_QSPI_ECC_ACCCTRL					0x78
#define SOCFPGA_ECC_QSPI_ECC_STARTACC					0x7C
#define SOCFPGA_ECC_QSPI_ECC_WDCTRL					0x80

/* IOSSM mailbox address */
#define IOSSM_CMD_PARAM							0x18400438
#define IOSSM_CMD_TRIG_OP						0x1840043C
#define IOSSM_CMD_RESP_STATUS						0x1840045C

#define DMA0_STREAM_CTRL_REG						0x8051217C
#define DMA1_STREAM_CTRL_REG						0x80512180
#define SDM_STREAM_CTRL_REG						0x80512184
#define USB2_STREAM_CTRL_REG						0x80512188
#define USB3_STREAM_CTRL_REG						0x8051218C
#define SDMMC_STREAM_CTRL_REG						0x80512190
#define NAND_STREAM_CTRL_REG						0x80512194
#define ETR_STREAM_CTRL_REG						0x80512198
#define TSN0_STREAM_CTRL_REG						0x8051219C
#define TSN1_STREAM_CTRL_REG						0x805121A0
#define TSN2_STREAM_CTRL_REG						0x805121A4

/* Stream ID configuration value for Agilex72 */
#define TSN0								0x00010001
#define TSN1								0x00020002
#define TSN2								0x00030003
#define NAND								0x00040004
#define SDMMC								0x00050005
#define USB0								0x00060006
#define USB1								0x00070007
#define DMA0								0x00080008
#define DMA1								0x00090009
#define SDM								0x000A000A
#define CORE_SIGHT_DEBUG						0x000B000B

/* JTAG ID value for Agilex72*/
#define A590_JTAG_ID							0x9000
#define A594_JTAG_ID							0x40009000
/* SM4 */
#define A5C0_JTAG_ID							0xC000
/* SM4 B0 */
#define A5C4_JTAG_ID							0x4000C000
#define A5D0_JTAG_ID							0xD000
#define A5D4_JTAG_ID							0x4000D000
/* SM7 */
#define A5F0_JTAG_ID							0xF000
/* SM7 B0 */
#define A5F4_JTAG_ID							0x4000F000
#define A510_JTAG_ID							0x1000
#define A514_JTAG_ID							0x40001000
#define A530_JTAG_ID							0x3000
#define A534_JTAG_ID							0x40003000
#define JTAG_ID_MASK							0xF000F000
#define A36F0_JTAG_ID							0x0360F0DD
#define SUB_JTAG_ID_MASK						0xCFF0FFFF

/* Field Masking */
#define SYSMGR_SDMMC_DRVSEL(x)						(((x) & 0x7) << 0)
#define SYSMGR_SDMMC_SMPLSEL(x)						(((x) & 0x7) << 4)

#define SYSMGR_F2S_BRIDGE_CTRL_EN					BIT(0)
#define SYSMGR_SOC_BRIDGE_CTRL_EN					BIT(0)
#define SYSMGR_LWSOC_BRIDGE_CTRL_EN					BIT(1)
#define IDLE_DATA_LWSOC2FPGA						BIT(4)
#define IDLE_DATA_SOC2FPGA						BIT(0)
#define IDLE_DATA_MASK							(IDLE_DATA_LWSOC2FPGA \
									| IDLE_DATA_SOC2FPGA)
#define SYSMGR_ECC_OCRAM_MASK						BIT(1)
#define SYSMGR_ECC_DDR0_MASK						BIT(16)
#define SYSMGR_ECC_DDR1_MASK						BIT(17)

#define WSTREAMIDEN_REG_CTRL						BIT(0)
#define RSTREAMIDEN_REG_CTRL						BIT(1)
#define WMMUSECSID_REG_VAL						BIT(4)
#define RMMUSECSID_REG_VAL						BIT(5)

#define SYSMGR_USB3_MISC0_RST_PUL_OVRD					BIT(12)
#define SYSMGR_USB3_MISC0_PORT_OVR_CURR_PIPE_PWR			BIT(14)

/* Macros */
#define SOCFPGA_ECC_QSPI(_reg)						(SOCFPGA_ECC_QSPI_REG_BASE \
									+ (SOCFPGA_ECC_QSPI_##_reg))

#define SOCFPGA_SYSMGR(_reg)		(SOCFPGA_SYSMGR_REG_BASE + \
					 (SOCFPGA_SYSMGR_##_reg))

#define SOCFPGA_LS_SYSMGR(_reg)		(SOCFPGA_LS_SYSMGR_REG_BASE + \
					 (SOCFPGA_LSP_SYSMGR_##_reg))

#define SOCFPGA_HS_SYSMGR(_reg)		(SOCFPGA_HS_SYSMGR_REG_BASE + \
					 (SOCFPGA_HSP_SYSMGR_##_reg))

#define ENABLE_STREAMID							WSTREAMIDEN_REG_CTRL \
									| RSTREAMIDEN_REG_CTRL
#define ENABLE_STREAMID_SECURE_TX					WSTREAMIDEN_REG_CTRL \
									| RSTREAMIDEN_REG_CTRL \
									| WMMUSECSID_REG_VAL \
									| RMMUSECSID_REG_VAL

#endif /* AGILEX72_SOCFPGA_SYSTEM_MANAGER_H */
