/*
 * Copyright (c) 2003-2016  Cavium Inc. (support@cavium.com). All rights
 * reserved.
 * Copyright (c) 2018 Facebook Inc.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* Macros used by ATF */

#define cavm_read8(addr)	(*(volatile uint8_t *)(addr))
#define cavm_read16(addr)	cavm_le16_to_cpu(*(volatile uint16_t *)(addr))
#define cavm_read32(addr)	cavm_le32_to_cpu(*(volatile uint32_t *)(addr))
#define cavm_read64(addr)	cavm_le64_to_cpu(*(volatile uint64_t *)(addr))

#define cavm_write8(addr, val)	(*(volatile uint8_t *)(addr) = (val))
#define cavm_write16(addr, val)	(*(volatile uint16_t *)(addr) = cavm_cpu_to_le16((val)))
#define cavm_write32(addr, val)	(*(volatile uint32_t *)(addr) = cavm_cpu_to_le32((val)))
#define cavm_write64(addr, val)	(*(volatile uint64_t *)(addr) = cavm_cpu_to_le64((val)))

/**
 * Macro to get the physical address of a CSR on a node
 */
#define CSR_PA(node, csr) ((csr) | ((uint64_t)(node) << 44))

#define CAVM_BGXX_PF_BAR0(x)		CAVM_BGX_BAR_E_BGXX_PF_BAR0(x)
#define CAVM_BGXX_PF_BAR0_SIZE	CAVM_BGX_BAR_E_BGXX_PF_BAR0_SIZE
#define offset_CAVM_BGXX_CMR_RX_LMACS(x)  (CAVM_BGXX_CMR_RX_LMACS(x) - CAVM_BGXX_PF_BAR0(x))
#define offset_CAVM_BGXX_CMRX_CONFIG(x,y) (CAVM_BGXX_CMRX_CONFIG(x,y) - CAVM_BGXX_PF_BAR0(x))
#define offset_CAVM_BGXX_SPUX_STATUS1(x,y) (CAVM_BGXX_SPUX_STATUS1(x,y) - CAVM_BGXX_PF_BAR0(x))
#define offset_CAVM_BGXX_CMRX_RX_STAT1(x,y) (CAVM_BGXX_CMRX_RX_STAT1(x,y) - CAVM_BGXX_PF_BAR0(x))
#define offset_CAVM_BGXX_CMRX_TX_STAT5(x,y) (CAVM_BGXX_CMRX_TX_STAT5(x,y) - CAVM_BGXX_PF_BAR0(x))

#define CAVM_CIM_CSR_BASE		0x87B000061180
#define CAVM_CIM_CSR_SIZE		0x179B000	 

#define CAVM_ECAMX_PF_BAR2(x)	CAVM_ECAM_BAR_E_ECAMX_PF_BAR2(x)
#define CAVM_ECAMX_PF_BAR2_SIZE	CAVM_ECAM_BAR_E_ECAMX_PF_BAR2_SIZE 

#define CAVM_DAP_PF_BAR0   		CAVM_DAP_BAR_E_DAP_PF_BAR0
#define CAVM_DAP_PF_BAR0_SIZE	CAVM_DAP_BAR_E_DAP_PF_BAR0_SIZE
#define offset_CAVM_DAP_IMP_DAR	(CAVM_DAP_IMP_DAR - CAVM_DAP_PF_BAR0)


#define CAVM_GPIO_PF_BAR0		CAVM_GPIO_BAR_E_GPIO_PF_BAR0
#define CAVM_GPIO_PF_BAR0_SIZE	CAVM_GPIO_BAR_E_GPIO_PF_BAR0_SIZE
#define CAVM_GPIO_PF_BAR4		CAVM_GPIO_BAR_E_GPIO_PF_BAR4
#define CAVM_GPIO_PF_BAR4_SIZE	CAVM_GPIO_BAR_E_GPIO_PF_BAR4_SIZE
#define offset_CAVM_GPIO_RX_DAT	(CAVM_GPIO_RX_DAT - CAVM_GPIO_PF_BAR0)
#define offset_CAVM_GPIO_TX_CLR	(CAVM_GPIO_TX_CLR - CAVM_GPIO_PF_BAR0)
#define offset_CAVM_GPIO_TX_SET	(CAVM_GPIO_TX_SET - CAVM_GPIO_PF_BAR0)
#define offset_CAVM_GPIO_BIT_CFGX(x)	(CAVM_GPIO_BIT_CFGX(x) - CAVM_GPIO_PF_BAR0)
#define offset_CAVM_GPIO_INTRX(x)	(CAVM_GPIO_INTRX(x) - CAVM_GPIO_PF_BAR0)

#define CAVM_GPIO_PIN_SEL_E_SGPIO_SDATAOUTX(x)	          \
	(CAVIUM_IS_MODEL(CAVIUM_CN81XX) 		  \
	 ? CAVM_GPIO_PIN_SEL_E_SGPIO_SDATAOUTX_CN81XX(x)	  \
	   : (CAVIUM_IS_MODEL(CAVIUM_CN83XX))		  \
              ? CAVM_GPIO_PIN_SEL_E_SGPIO_SDATAOUTX_CN83XX(x)  \
		: CAVM_GPIO_PIN_SEL_E_SGPIO_SDATAOUTX_CN88XX(x))

#define CAVM_GPIO_PIN_SEL_E_SGPIO_SCLOCK	          	  \
	(CAVIUM_IS_MODEL(CAVIUM_CN81XX) 		  \
	 ? CAVM_GPIO_PIN_SEL_E_SGPIO_SCLOCK_CN81XX	  	  \
	   : (CAVIUM_IS_MODEL(CAVIUM_CN83XX))		  \
              ? CAVM_GPIO_PIN_SEL_E_SGPIO_SCLOCK_CN83XX  	  \
		: CAVM_GPIO_PIN_SEL_E_SGPIO_SCLOCK_CN88XX)

#define CAVM_GPIO_PIN_SEL_E_SGPIO_SLOAD	          	  \
	(CAVIUM_IS_MODEL(CAVIUM_CN81XX) 		  \
	 ? CAVM_GPIO_PIN_SEL_E_SGPIO_SLOAD_CN81XX	  	  \
	   : (CAVIUM_IS_MODEL(CAVIUM_CN83XX))		  \
              ? CAVM_GPIO_PIN_SEL_E_SGPIO_SLOAD_CN83XX  	  \
		: CAVM_GPIO_PIN_SEL_E_SGPIO_SLOAD_CN88XX)


#define CAVM_GIC_PF_BAR0		CAVM_GIC_BAR_E_GIC_PF_BAR0
#define CAVM_GIC_PF_BAR0_SIZE	CAVM_GIC_BAR_E_GIC_PF_BAR0_SIZE
#define CAVM_GIC_PF_BAR2		CAVM_GIC_BAR_E_GIC_PF_BAR2
#define CAVM_GIC_PF_BAR2_SIZE	CAVM_GIC_BAR_E_GIC_PF_BAR2_SIZE
#define CAVM_GIC_PF_BAR4		CAVM_GIC_BAR_E_GIC_PF_BAR4
#define CAVM_GIC_PF_BAR4_SIZE	CAVM_GIC_BAR_E_GIC_PF_BAR4_SIZE
#define offset_CAVM_GICD_ISENABLERX(x) (CAVM_GICD_ISENABLERX(x) - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICD_SETSPI_NSR	(CAVM_GICD_SETSPI_NSR - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GIC_CFG_CTLR	(CAVM_GIC_CFG_CTLR - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICD_IGROUPRX(x)	(CAVM_GICD_IGROUPRX(x) - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICD_IPRIORITYRX(x) (CAVM_GICD_IPRIORITYRX(x) - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICRX_IGROUPR0(x)  (CAVM_GICRX_IGROUPR0(x) - CAVM_GIC_PF_BAR4)
#define offset_CAVM_GICRX_ISENABLER0(x)  (CAVM_GICRX_ISENABLER0(x) - CAVM_GIC_PF_BAR4)
#define offset_CAVM_GICRX_WAKER(x)	(CAVM_GICRX_WAKER(x) - CAVM_GIC_PF_BAR4)
#define offset_CAVM_GICD_SCTLR	(CAVM_GICD_SCTLR - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICD_IROUTERX(x)	(CAVM_GICD_IROUTERX(x) - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICD_IGRPMODRX(x) (CAVM_GICRX_IGRPMODR0(x) - CAVM_GIC_PF_BAR4)
#define offset_CAVM_GICD_ICFGRX(x)	(CAVM_GICD_ICFGRX(x) - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICD_NSACRX(x)	(CAVM_GICD_NSACRX(x) - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICRX_IGRPMODR0(x)  (CAVM_GICD_IGROUPRX(x) - CAVM_GIC_PF_BAR0)
#define offset_CAVM_GICD_CLRSPI_SR	(CAVM_GICD_CLRSPI_SR - CAVM_GIC_PF_BAR0)

#define CAVM_GTI_PF_BAR0		CAVM_GTI_BAR_E_GTI_PF_BAR0
#define CAVM_GTI_PF_BAR0_SIZE	CAVM_GTI_BAR_E_GTI_PF_BAR0_SIZE
#define CAVM_GTI_PF_BAR4		CAVM_GTI_BAR_E_GTI_PF_BAR4
#define CAVM_GTI_PF_BAR4_SIZE	CAVM_GTI_BAR_E_GTI_PF_BAR4_SIZE
#define offset_CAVM_GTI_RD_CNTCV	(CAVM_GTI_RD_CNTCV - CAVM_GTI_PF_BAR0)
#define offset_CAVM_GTI_CC_CNTADD	(CAVM_GTI_CC_CNTADD - CAVM_GTI_PF_BAR0)
#define offset_CAVM_GTI_CWD_INT	(CAVM_GTI_CWD_INT - CAVM_GTI_PF_BAR0)
#define offset_CAVM_GTI_CWD_INT_ENA_SET (CAVM_GTI_CWD_INT_ENA_SET - CAVM_GTI_PF_BAR0)
#define offset_CAVM_GTI_CWD_WDOGX(x) (CAVM_GTI_CWD_WDOGX(x) - CAVM_GTI_PF_BAR0)
#define offset_CAVM_GTI_MSIX_VECX_ADDR(x) (CAVM_GTI_MSIX_VECX_ADDR(x) - CAVM_GTI_PF_BAR4)
#define offset_CAVM_GTI_MSIX_VECX_CTL(x)  (CAVM_GTI_MSIX_VECX_CTL(x) - CAVM_GTI_PF_BAR4)
#define offset_CAVM_GTI_CWD_POKEX(x)	(CAVM_GTI_CWD_POKEX(x) - CAVM_GTI_PF_BAR0)
#define CAVM_GTI_INT_VEC_E_CORE_WDOG0_INT CAVM_GTI_INT_VEC_E_CORE_WDOGX_INT(0)

#define CAVM_GSERX_PF_BAR0(x)	CAVM_GSER_BAR_E_GSERX_PF_BAR0(x)
#define CAVM_GSERX_PF_BAR0_SIZE	CAVM_GSER_BAR_E_GSERX_PF_BAR0_SIZE
#define offset_CAVM_GSERX_PHY_CTL(x)	(CAVM_GSERX_PHY_CTL(x) - CAVM_GSERX_PF_BAR0(x))
#define offset_CAVM_GSERX_CFG(x)	(CAVM_GSERX_CFG(x) - CAVM_GSERX_PF_BAR0(x))

#define CAVM_L2C_PF_BAR0		(0x87e080800000ll)
#define CAVM_L2C_PF_BAR0_SIZE	CAVM_L2C_BAR_E_L2C_PF_BAR0_SIZE
#define offset_CAVM_L2C_OCI_CTL	(CAVM_L2C_OCI_CTL - CAVM_L2C_PF_BAR0)

#define CAVM_L2C_CBCX_PF_BAR0(x)	CAVM_L2C_CBC_BAR_E_L2C_CBCX_PF_BAR0(x)
#define CAVM_L2C_CBCX_PF_BAR0_SIZE	CAVM_L2C_CBC_BAR_E_L2C_CBCX_PF_BAR0_SIZE
#define offset_CAVM_L2C_CBCX_INT_W1C(x) (CAVM_L2C_CBCX_INT_W1C(x) - CAVM_L2C_CBCX_PF_BAR0(x))

#define CAVM_L2C_MCIX_PF_BAR0(x)	CAVM_L2C_MCI_BAR_E_L2C_MCIX_PF_BAR0(x)
#define CAVM_L2C_MCIX_PF_BAR0_SIZE	CAVM_L2C_MCI_BAR_E_L2C_MCIX_PF_BAR0_SIZE
#define offset_CAVM_L2C_MCIX_INT_W1C(x) (CAVM_L2C_MCIX_INT_W1C(x) - CAVM_L2C_MCIX_PF_BAR0(x))

#define CAVM_L2C_TADX_PF_BAR0(x)	CAVM_L2C_TAD_BAR_E_L2C_TADX_PF_BAR0(x)
#define CAVM_L2C_TADX_PF_BAR0_SIZE	CAVM_L2C_TAD_BAR_E_L2C_TADX_PF_BAR0_SIZE
#define offset_CAVM_L2C_TADX_INT_W1C(x) (CAVM_L2C_TADX_INT_W1C(x) - CAVM_L2C_TADX_PF_BAR0(x))

#define CAVM_LMCX_PF_BAR0(x)		CAVM_LMC_BAR_E_LMCX_PF_BAR0(x)
#define CAVM_LMCX_PF_BAR0_SIZE	CAVM_LMC_BAR_E_LMCX_PF_BAR0_SIZE
#define offset_CAVM_LMCX_CONFIG(x)	(CAVM_LMCX_CONFIG(x) - CAVM_LMCX_PF_BAR0(x))
#define offset_CAVM_LMCX_DDR_PLL_CTL(x) (CAVM_LMCX_DDR_PLL_CTL(x) - CAVM_LMCX_PF_BAR0(x))
#define offset_CAVM_LMCX_INT(x)	(CAVM_LMCX_INT(x) - CAVM_LMCX_PF_BAR0(x))

#define CAVM_IOBNX_PF_BAR0(x)	(0x87e0f0000000ll + 0x1000000ll * (x))
#define CAVM_IOBNX_PF_BAR0_SIZE	CAVM_IOBN_BAR_E_IOBNX_PF_BAR0_SIZE

#define CAVM_MIO_BOOT_PF_BAR0	CAVM_MIO_BOOT_BAR_E_MIO_BOOT_PF_BAR0
#define CAVM_MIO_BOOT_PF_BAR0_SIZE	CAVM_MIO_BOOT_BAR_E_MIO_BOOT_PF_BAR0_SIZE

#define CAVM_MIO_EMM_PF_BAR0		CAVM_MIO_EMM_BAR_E_MIO_EMM_PF_BAR0
#define CAVM_MIO_EMM_PF_BAR0_SIZE	CAVM_MIO_EMM_BAR_E_MIO_EMM_PF_BAR0_SIZE
#define offset_CAVM_MIO_EMM_CFG	(CAVM_MIO_EMM_CFG - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_STS_MASK (CAVM_MIO_EMM_STS_MASK - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_SWITCH	(CAVM_MIO_EMM_SWITCH - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_WDOG	(CAVM_MIO_EMM_WDOG - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_RSP_LO	(CAVM_MIO_EMM_RSP_LO - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_RCA	(CAVM_MIO_EMM_RCA - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_RSP_STS	(CAVM_MIO_EMM_RSP_STS - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_CMD	(CAVM_MIO_EMM_CMD - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_DMA_ADR	(CAVM_MIO_EMM_DMA_ADR - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_DMA_CFG	(CAVM_MIO_EMM_DMA_CFG - CAVM_MIO_EMM_PF_BAR0)
#define offset_CAVM_MIO_EMM_DMA	(CAVM_MIO_EMM_DMA - CAVM_MIO_EMM_PF_BAR0)

#define CAVM_MIO_TWSX_PF_BAR0(x)	CAVM_MIO_TWS_BAR_E_MIO_TWSX_PF_BAR0(x)
#define CAVM_MIO_TWSX_PF_BAR0_SIZE	CAVM_MIO_TWS_BAR_E_MIO_TWSX_PF_BAR0_SIZE
#define offset_CAVM_MIO_TWSX_SW_TWSI(x) (CAVM_MIO_TWSX_SW_TWSI(x) - CAVM_MIO_TWSX_PF_BAR0(x))
#define offset_CAVM_MIO_TWSX_TWSI_SW(x) (CAVM_MIO_TWSX_TWSI_SW(x) - CAVM_MIO_TWSX_PF_BAR0(x))
#define offset_CAVM_MIO_TWSX_INT(x) 	(CAVM_MIO_TWSX_INT(x) - CAVM_MIO_TWSX_PF_BAR0(x))
#define offset_CAVM_MIO_TWSX_INT_ENA_W1S(x) (CAVM_MIO_TWSX_INT_ENA_W1S(x) - CAVM_MIO_TWSX_PF_BAR0(x))

#define CAVM_MPI_PF_BAR0		CAVM_MPI_BAR_E_MPI_PF_BAR0
#define CAVM_MPI_PF_BAR0_SIZE	CAVM_MPI_BAR_E_MPI_PF_BAR0_SIZE
#define offset_CAVM_MPI_CFG		(CAVM_MPI_CFG - CAVM_MPI_PF_BAR0)
#define offset_CAVM_MPI_DATX(x)	(CAVM_MPI_DATX(x) - CAVM_MPI_PF_BAR0)
#define offset_CAVM_MPI_STS		(CAVM_MPI_STS - CAVM_MPI_PF_BAR0)
#define offset_CAVM_MPI_TX		(CAVM_MPI_TX - CAVM_MPI_PF_BAR0)

#define CAVM_MRML_PF_BAR0		CAVM_MRML_BAR_E_MRML_PF_BAR0
#define CAVM_MRML_PF_BAR0_SIZE	CAVM_MRML_BAR_E_MRML_PF_BAR0_SIZE
#define offset_CAVM_MRML_NCBX_SDEV(x) (CAVM_MRML_NCBX_SDEV(x) - CAVM_MRML_PF_BAR0)
#define offset_CAVM_MRML_RSLX_SDEV(x) (CAVM_MRML_RSLX_SDEV(x) - CAVM_MRML_PF_BAR0)

#define CAVM_OCX_PF_BAR0		CAVM_OCX_BAR_E_OCX_PF_BAR0
#define CAVM_OCX_PF_BAR0_SIZE	CAVM_OCX_BAR_E_OCX_PF_BAR0_SIZE
#define offset_CAVM_OCX_COM_INT	(CAVM_OCX_COM_INT - CAVM_OCX_PF_BAR0)
#define offset_CAVM_OCX_COM_LINKX_INT(x) (CAVM_OCX_COM_LINKX_INT(x) - CAVM_OCX_PF_BAR0)
#define offset_CAVM_OCX_LNEX_INT(x)	(CAVM_OCX_LNEX_INT(x) - CAVM_OCX_PF_BAR0)

#define CAVM_PCCPF_CSR_BASE 0x0
#define offset_CAVM_PCCPF_XXX_BAR0U		(CAVM_PCCPF_XXX_BAR0L - CAVM_PCCPF_CSR_BASE)
#define offset_CAVM_PCCPF_XXX_BAR2U		(CAVM_PCCPF_XXX_BAR2L - CAVM_PCCPF_CSR_BASE)
#define offset_CAVM_PCCPF_XXX_BAR4U		(CAVM_PCCPF_XXX_BAR4L - CAVM_PCCPF_CSR_BASE)
#define offset_CAVM_PCCPF_XXX_SRIOV_BAR0U	(CAVM_PCCPF_XXX_SRIOV_BAR0L - CAVM_PCCPF_CSR_BASE)
#define offset_CAVM_PCCPF_XXX_SRIOV_BAR2U	(CAVM_PCCPF_XXX_SRIOV_BAR2L - CAVM_PCCPF_CSR_BASE)
#define offset_CAVM_PCCPF_XXX_VSEC_CTL	(CAVM_PCCPF_XXX_VSEC_CTL - CAVM_PCCPF_CSR_BASE)

#define CAVM_PEMX_PF_BAR0(x)		CAVM_PEM_BAR_E_PEMX_PF_BAR0(x)
#define CAVM_PEMX_PF_BAR0_SIZE	CAVM_PEM_BAR_E_PEMX_PF_BAR0_SIZE

#define CAVM_PEM_INT_VEC_E_INTA   (CAVIUM_IS_MODEL(CAVIUM_CN81XX)      \
			   ? CAVM_PEM_INT_VEC_E_INTA_CN81XX		  \
			     : (CAVIUM_IS_MODEL(CAVIUM_CN83XX))		  \
				? CAVM_PEM_INT_VEC_E_INTA_CN83XX	  \
				  : CAVM_PEM_INT_VEC_E_INTA_CN88XX)

#define CAVM_PEM_INT_VEC_E_INT_SUM   (CAVIUM_IS_MODEL(CAVIUM_CN81XX)      \
			   ? CAVM_PEM_INT_VEC_E_INT_SUM_CN81XX		  \
			     : (CAVIUM_IS_MODEL(CAVIUM_CN83XX))		  \
				? CAVM_PEM_INT_VEC_E_INT_SUM_CN83XX	  \
				  : CAVM_PEM_INT_VEC_E_INT_SUM_CN88XX)

#define CAVM_RST_PF_BAR0		CAVM_RST_BAR_E_RST_PF_BAR0
#define CAVM_RST_PF_BAR0_SIZE	CAVM_RST_BAR_E_RST_PF_BAR0_SIZE
#define offset_CAVM_RST_REF_CNTR	(CAVM_RST_REF_CNTR - CAVM_RST_PF_BAR0)
#define offset_CAVM_RST_BOOT		(CAVM_RST_BOOT - CAVM_RST_PF_BAR0)
#define offset_CAVM_RST_PP_RESET	(CAVM_RST_PP_RESET - CAVM_RST_PF_BAR0)
#define offset_CAVM_RST_PP_PENDING	(CAVM_RST_PP_PENDING - CAVM_RST_PF_BAR0)
#define offset_CAVM_RST_DBG_RESET	(CAVM_RST_DBG_RESET - CAVM_RST_PF_BAR0)
#define offset_CAVM_RST_SOFT_RST	(CAVM_RST_SOFT_RST - CAVM_RST_PF_BAR0)
#define offset_CAVM_RST_OCX		(CAVM_RST_OCX - CAVM_RST_PF_BAR0)

#define CAVM_SATAX_PF_BAR0(x)	CAVM_SATA_BAR_E_SATAX_PF_BAR0(x)
#define CAVM_SATAX_PF_BAR0_SIZE	CAVM_SATA_BAR_E_SATAX_PF_BAR0_SIZE

#define CAVM_SGP_PF_BAR0		CAVM_SGP_BAR_E_SGP_PF_BAR0
#define CAVM_SGP_PF_BAR0_SIZE	CAVM_SGP_BAR_E_SGP_PF_BAR0_SIZE
#define offset_CAVM_SGP_CFG0		(CAVM_SGP_CFG0 - CAVM_SGP_PF_BAR0)
#define offset_CAVM_SGP_IMP_CLK	(CAVM_SGP_IMP_CLK - CAVM_SGP_PF_BAR0)
#define offset_CAVM_SGP_IMP_CTL	(CAVM_SGP_IMP_CTL - CAVM_SGP_PF_BAR0)
#define offset_CAVM_SGP_TX_GP_CFG	(CAVM_SGP_TX_GP_CFG - CAVM_SGP_PF_BAR0)
#define offset_CAVM_SGP_TXX(x)	(CAVM_SGP_TXX(x) - CAVM_SGP_PF_BAR0)
#define offset_CAVM_SGP_IMP_DRIVEX(x) (CAVM_SGP_IMP_DRIVEX(x) - CAVM_SGP_PF_BAR0)

#define CAVM_SLIX_PF_BAR0(x)   (CAVIUM_IS_MODEL(CAVIUM_CN81XX) 		  \
			   ? CAVM_SLI_BAR_E_SLIX_PF_BAR0_CN81XX(x)		  \
			     : (CAVIUM_IS_MODEL(CAVIUM_CN83XX))		  \
                                ? CAVM_SLI_BAR_E_SLIX_PF_BAR0_CN83XX(x)	  \
				  : CAVM_SLI_BAR_E_SLIX_PF_BAR0_CN88XX(x))

#define CAVM_SLIX_PF_BAR0_SIZE   (CAVIUM_IS_MODEL(CAVIUM_CN81XX) 		  \
			     ? CAVM_SLI_BAR_E_SLIX_PF_BAR0_CN81XX_SIZE	  \
			       : (CAVIUM_IS_MODEL(CAVIUM_CN83XX))	  \
                                  ? CAVM_SLI_BAR_E_SLIX_PF_BAR0_CN83XX_SIZE	  \
				    : CAVM_SLI_BAR_E_SLIX_PF_BAR0_CN88XX_SIZE)

#define CAVM_SMMUX_PF_BAR0(x)	(0x830000000000ll + 0x1000000000ll * (x))
#define CAVM_SMMUX_PF_BAR0_SIZE	CAVM_SMMU_BAR_E_SMMUX_PF_BAR0_SIZE

#define offset_CAVM_SMMUX_SSDRX(x,y) (CAVM_SMMUX_SSDRX(x,y) - CAVM_SMMUX_PF_BAR0(x))
#define offset_CAVM_SMMUX_SCR0(x)	(CAVM_SMMUX_SCR0(x) - CAVM_SMMUX_PF_BAR0(x))

#define CAVM_UAAX_PF_BAR0(x)   (CAVIUM_IS_MODEL(CAVIUM_CN81XX) 		  \
			   ? CAVM_UAA_BAR_E_UAAX_PF_BAR0_CN81XX(x)		  \
			     : (CAVIUM_IS_MODEL(CAVIUM_CN83XX))		  \
                                ? CAVM_UAA_BAR_E_UAAX_PF_BAR0_CN83XX(x)	  \
				  : CAVM_UAA_BAR_E_UAAX_PF_BAR0_CN88XX(x))

#define CAVM_UAAX_PF_BAR0_SIZE	CAVM_UAA_BAR_E_UAAX_PF_BAR0_CN88XX_SIZE


/**
 * Get the The core ID (0...48)
 *
 * @return The core ID
 */
static inline int cavm_core_id(void)  __attribute__ ((always_inline));
static inline int cavm_core_id(void)
{
	uint64_t mpidr;
	int aff1, aff0;

	__asm__ volatile ("mrs %0, MPIDR_EL1" : "=r" (mpidr) );
	aff1 = (mpidr >> 8) & 0xff;
	aff0 = (mpidr >> 0) & 0xff;
	/* Aff1 * 16 + Aff0 */
	return (aff1 << 4) + aff0;
}
