#
# Copyright (c) 2022-2025, MediaTek Inc. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

# call add_defined_option to evaluate MTK defined value
DEFINED_OPTIONS := \
	CONFIG_MTK_CPU_PM_ARCH \
	CONFIG_MTK_CPU_PM_SUPPORT \
	CONFIG_MTK_CPU_SUSPEND_EN \
	CONFIG_MTK_DISABLE_CACHE_AS_RAM \
	CONFIG_MTK_MCUSYS \
	CONFIG_MTK_MTCMOS \
	CONFIG_MTK_PM_ARCH \
	CONFIG_MTK_PM_SUPPORT \
	CONFIG_MTK_SMMU_SID \
	CONFIG_MTK_SMP_EN \
	CONFIG_MTK_SUPPORT_SYSTEM_SUSPEND \
	MTK_ADAPTED \
	MTK_BL31_AS_BL2 \
	MTK_BL33_IS_64BIT \
	MTK_EXTRA_LINKERFILE \
	MTK_PUBEVENT_ENABLE \
	MTK_SIP_KERNEL_BOOT_ENABLE \
	MTK_SOC \
	PLAT_EXTRA_RODATA_INCLUDES \
	PLAT_XLAT_TABLES_DYNAMIC \
	UART_BAUDRATE \
	UART_CLOCK

$(foreach opt, $(DEFINED_OPTIONS),$(eval $(call add_defined_option,$(opt))))
