#!/usr/bin/env python3
#
# Copyright (c) 2026, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
"""Generate and commit reviewers.config from docs/about/maintainers.rst."""

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path


COMMIT_SUBJECT = "reviewers plugin: synchronise to master's maintainers.rst"
COMMIT_BODY = (
    "This commit was auto-generated by scripts/generate_reviewers_config.py\n"
    "in the master branch based on docs/about/maintainers.rst."
)
HELP_HEADER = """Prepare the supplied worktree before running this script:

  git fetch origin refs/meta/config:refs/remotes/origin/meta/config
  git checkout origin/meta/config

After this script creates the commit, push it for review with:

  git push origin HEAD:refs/for/refs/meta/config
"""
DIRECTIVE_RE = re.compile(r"^:\|([MCF])\|:\s*(.*)$")
EMAIL_RE = re.compile(r"<([^<>]+)>")
LTS_BRANCH_RE = re.compile(r"^v(\d+\.\d+) branch$")
HEADING_CHARS = frozenset("=-~^\"`:+*#<>")


def run_git(worktree, *args):
    command = ["git", "-C", str(worktree), *args]
    try:
        return subprocess.run(
            command, check=True, text=True, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        ).stdout.strip()
    except subprocess.CalledProcessError as error:
        message = error.stderr.strip() or error.stdout.strip()
        raise RuntimeError(f"{' '.join(command)} failed: {message}") from error


def is_heading_underline(line):
    stripped = line.strip()
    return (
        len(stripped) >= 3
        and len(set(stripped)) == 1
        and stripped[0] in HEADING_CHARS
    )


def parse_email(value, line_num):
    email_match = EMAIL_RE.search(value)
    if email_match is None:
        raise ValueError(f"missing email address in directive at line {line_num}")
    return email_match.group(1)


def path_to_filter(path, source_root):
    """Convert a maintainer-file path into a Gerrit file-filter regex."""
    filesystem_path = path.replace(r"\_", "_").replace(r"\*", "*")
    filter_path = path.replace(r"\_", "_").replace(r".\*", ".*").replace(r"\*", ".*")

    if filter_path.endswith("/"):
        return filter_path + ".*"

    if ".*" not in filter_path and (source_root / filesystem_path).is_dir():
        return filter_path + "/.*"

    return filter_path


def parse_directive(line, line_num):
    match = DIRECTIVE_RE.match(line)
    if not match:
        return (None, None,)

    directive, value = match.groups()
    if not value:
        raise ValueError(f"empty {directive} directive at line {line_num}")

    return (directive, value,)


def parse_lts_maintainers(lines):
    lts_start = lines.index(".. _lts maintainers:")
    code_owner_start = lines.index(".. _code owners:")
    branches = {}

    for index in range(lts_start, code_owner_start):
        line = lines[index]
        line_num = index + 1

        if line_num < code_owner_start and is_heading_underline(lines[index + 1]):
            heading = line.strip()
            branch_match = LTS_BRANCH_RE.match(heading)
            current_branch = branch_match.group(1) if branch_match else None
            if current_branch is not None:
                branches[current_branch] = []
            continue

        directive, value = parse_directive(line, line_num)
        if not directive:
            continue
        if directive != "M":
            continue
        if current_branch is not None:
            branches[current_branch].append(parse_email(value, line_num))

    return branches


def parse_code_owners(lines, source_root):
    code_owner_start = lines.index(".. _code owners:")

    maintainers = []
    ccs = []
    filters = []
    saw_heading = False

    for index in range(code_owner_start, len(lines)):
        line = lines[index]
        line_num = index + 1
        if index + 1 < len(lines) and is_heading_underline(lines[index + 1]):
            maintainers = []
            ccs = []
            saw_heading = True
            continue

        directive, value = parse_directive(line, line_num)
        if not directive:
            continue

        if not saw_heading:
            raise ValueError(f"directive before a code-owner heading: at line {line_num}")

        if directive in "MC":
            (maintainers if directive == "M" else ccs).append(parse_email(value, line_num))
            continue

        filter_path = path_to_filter(value, source_root)
        try:
            re.compile(filter_path)
        except re.error as error:
            raise ValueError(
                f"invalid file-filter regex '{filter_path}' at line {line_num}: {error}"
            ) from error
        filters.append((filter_path, maintainers[:], ccs[:]))

    return filters


def render_config(maintainers_path, source_root):
    """Render Gerrit reviewers.config content from the maintainer RST sections."""
    lines = maintainers_path.read_text(encoding="utf-8").splitlines()

    output = []
    lts_maintainers = parse_lts_maintainers(lines)
    for version, reviewers in lts_maintainers.items():
        output.append(f'[filter "branch:lts-v{version}"]')
        output.extend(f"    reviewer = {reviewer}" for reviewer in reviewers)
        output.append("")

    for filter_path, reviewers, filter_ccs in parse_code_owners(lines, source_root):
        output.append(f'[filter "branch:integration file:^{filter_path}"]')
        output.extend(f"    reviewer = {reviewer}" for reviewer in reviewers)
        output.extend(f"    cc = {cc}" for cc in filter_ccs)
        output.append("")
    return "\n".join(output)


def validate_worktree(worktree):
    worktree = worktree.resolve()
    if not worktree.is_dir():
        raise ValueError(f"worktree does not exist: {worktree}")

    top_level = Path(run_git(worktree, "rev-parse", "--show-toplevel")).resolve()
    if top_level != worktree:
        raise ValueError(f"--worktree must name the worktree root: {worktree}")

    if run_git(worktree, "status", "--porcelain"):
        raise ValueError(f"worktree is not clean: {worktree}")
    return worktree


def validate_config(content, directory):
    """Use Git's config parser before replacing the target file."""
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=directory, prefix="reviewers.config.",
        delete=False
    ) as temporary_file:
        temporary_file.write(content)
        temporary_path = Path(temporary_file.name)
    try:
        subprocess.run(
            ["git", "config", "--file", str(temporary_path), "--list"],
            check=True, text=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE
        )
    except subprocess.CalledProcessError as error:
        raise RuntimeError(f"generated configuration is invalid: {error.stderr.strip()}") from error
    finally:
        temporary_path.unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(
        description=HELP_HEADER,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--worktree", type=Path, required=True,
        help="existing clean worktree checked out at origin/meta/config"
    )
    arguments = parser.parse_args()

    source_root = Path(__file__).resolve().parent.parent
    maintainers_path = source_root / "docs" / "about" / "maintainers.rst"
    worktree = validate_worktree(arguments.worktree)
    content = render_config(maintainers_path, source_root)
    validate_config(content, worktree)

    target = worktree / "reviewers.config"
    previous_content = target.read_text(encoding="utf-8") if target.exists() else ""
    if content == previous_content:
        print("reviewers.config is already up to date")
        return

    target.write_text(content, encoding="utf-8")
    run_git(worktree, "add", "reviewers.config")
    run_git(worktree, "commit", "-m", COMMIT_SUBJECT, "-m", COMMIT_BODY, "-s")
    print(f"updated and committed {target}")


if __name__ == "__main__":
    try:
        main()
    except (OSError, RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        sys.exit(1)
