/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <lib/mmio.h>
#include <lib/utils_def.h>
#include <xpu_target_info.h>

/* QCS9075: modem-related XPU types removed from interrupt mapping */
struct xpu_err_pos_to_hal_map xpu_err_pos_to_hal_map
	[ACC_XPU_ERR_INT_REG_NUM][ACC_XPU_ERR_NUM_PER_REG] = {
		{
			{ BIT(0), XPU_TYPE_PMIC_ARB },
			{ BIT(1), XPU_TYPE_AOSS_MPU },
			{ BIT(2), XPU_TYPE_BAM_BLSP1_DMA },
			{ BIT(3), XPU_TYPE_TCSR_REGS },
			{ BIT(4), XPU_TYPE_BAM_BLSP2_DMA },
			{ BIT(5), XPU_TYPE_TCSR_MUTEX },
			{ BIT(6), XPU_TYPE_CRYPTO0_BAM },
			{ BIT(7), XPU_TYPE_IMEM_APU },
			{ BIT(8), XPU_TYPE_DCC },
			{ BIT(9), XPU_TYPE_SEC_CTRL_APU },
			{ BIT(10), XPU_TYPE_LPASS_XPU_AUD },
			{ BIT(11), XPU_TYPE_LPASS_WSA2_DMA_MPU },
			{ BIT(12), XPU_TYPE_LPASS_XPU_AUD_SB },
			{ BIT(13), XPU_TYPE_RAMBLUR_PIMEM_APU },
			{ BIT(14), XPU_TYPE_RAMBLUR_PIMEM_MPU },
			{ BIT(15), XPU_TYPE_QUP_AXI },
			{ BIT(16), XPU_TYPE_CNOC_AOSS_MPU },
			{ BIT(17), XPU_TYPE_CNOC_SNOC_MPU },
			{ BIT(18), XPU_TYPE_CNOC_SNOC_MS_MPU },
			{ BIT(19), XPU_TYPE_QM_MPU_CFG },
			{ BIT(20), XPU_TYPE_AOP_MS_MPU },
			{ BIT(21), XPU_TYPE_GCC_RPU },
			{ BIT(22), XPU_TYPE_TITAN_SS_APU2 },
			{ BIT(23), XPU_TYPE_BOOT_IMEM_SS_MPU },
			{ BIT(24), XPU_TYPE_UFS_ICE },
			{ BIT(25), XPU_TYPE_BIMC_MPU0 },
			{ BIT(26), XPU_TYPE_BIMC_MPU1 },
			{ BIT(27), XPU_TYPE_BIMC_MPU2 },
			{ BIT(28), XPU_TYPE_BIMC_MPU3 },
			{ BIT(29), XPU_TYPE_NOC_BROADCAST_MPU },
			{ BIT(30), XPU_TYPE_BOOT_ROM },
			{ BIT(31), XPU_TYPE_NOC_BROADCAST_MPU },
		},
		{
			{ BIT(0), XPU_TYPE_IMEM_MPU },
			{ BIT(1), XPU_TYPE_ANOC1_MPU },
			{ BIT(2), XPU_TYPE_ANOC2_MPU },
			{ BIT(3), XPU_TYPE_CRYPTO1_BAM },
			{ BIT(4), XPU_TYPE_SPDM_APU },
			{ BIT(5), XPU_TYPE_TITAN_SS_APU1 },
			{ BIT(6), XPU_TYPE_UFS_ICE },
			{ BIT(7), XPU_TYPE_MDSS0 },
			{ BIT(8), XPU_TYPE_TLMM },
			{ BIT(9), XPU_TYPE_COUNT },
			{ BIT(10), XPU_TYPE_CRYPTO1_CRYPTO_KM_APU },
			{ BIT(11), XPU_TYPE_IPA_0_GSI_TOP },
			{ BIT(12), XPU_TYPE_BAM_BLSP3_DMA },
			{ BIT(13), XPU_TYPE_DC_NOC_SHRM_MPU },
			{ BIT(14), XPU_TYPE_PKE_APU },
			{ BIT(15), XPU_TYPE_MDSS1 },
			{ BIT(16), XPU_TYPE_IPC_MPU },
			{ BIT(17), XPU_TYPE_ETH_MS_MPU },
			{ BIT(18), XPU_TYPE_LPASS_Q6SS_MPU },
			{ BIT(19), XPU_TYPE_LPASS_DEBUG_MPU },
			{ BIT(20), XPU_TYPE_LPASS_VA_MPU },
			{ BIT(21), XPU_TYPE_LPASS_WSA_MPU },
			{ BIT(22), XPU_TYPE_LPASS_CFG_MPU },
			{ BIT(23), XPU_TYPE_LPASS_RXTX_MPU },
			{ BIT(24), XPU_TYPE_COUNT },
			{ BIT(25), XPU_TYPE_COUNT },
			{ BIT(26), XPU_TYPE_CRYPTO0_CRYPTO_KM_APU },
			{ BIT(27), XPU_TYPE_HWKM_CFG_KM_APU },
			{ BIT(28), XPU_TYPE_UFS_MEM_ICE_KM_APU },
			{ BIT(29), XPU_TYPE_UFS_CARD_ICE_KM_APU },
			{ BIT(30), XPU_TYPE_TSCSS_MPU },
			{ BIT(31), XPU_TYPE_GIC_MS_MPU },
		},
		{
			{ BIT(0), XPU_TYPE_BIMC_MPU4 },
			{ BIT(1), XPU_TYPE_BIMC_MPU5 },
			{ BIT(2), XPU_TYPE_R52_MS_MPU },
			{ BIT(3), XPU_TYPE_SDC1_SDCC_ICE },
			{ BIT(4), XPU_TYPE_SDC1_SDCC_ICE_KM_APU },
			{ BIT(5), XPU_TYPE_COUNT },
			{ 0, 0 },
		},
	};

const struct xpu_intr_reg_dtls
	xpu_non_sec_intr_status_reg[ACC_XPU_ERR_INT_REG_NUM] = {
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_0_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_0_RMSK,
		},
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_1_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_1_RMSK,
		},
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_2_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_STATUS_REG_2_RMSK,
		},
	};

const struct xpu_intr_reg_dtls
	xpu_sec_intr_status_reg[ACC_XPU_ERR_INT_REG_NUM] = {
		{
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_0_ADDR,
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_0_RMSK,
		},
		{
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_1_ADDR,
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_1_RMSK,
		},
		{
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_2_ADDR,
			HWIO_TCSR_XPU3_SEC_IRQ_STATUS_REG_2_RMSK,
		},
	};

const struct xpu_intr_reg_dtls
	xpu_non_sec_intr_en_reg[ACC_XPU_ERR_INT_REG_NUM] = {
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_0_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_0_RMSK,
		},
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_1_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_1_RMSK,
		},
		{
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_2_ADDR,
			HWIO_TCSR_XPU3_NON_SEC_IRQ_ENABLE_0_REG_2_RMSK,
		},
	};

const struct xpu_intr_reg_dtls
	xpu_sec_intr_en_reg[ACC_XPU_ERR_INT_REG_NUM] = {
		{
			HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_0_ADDR,
			HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_0_RMSK,
		},
		{
			HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_1_ADDR,
			HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_1_RMSK,
		},
		{
			HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_2_ADDR,
			HWIO_TCSR_XPU3_SEC_IRQ_ENABLE_0_REG_2_RMSK,
		},
	};

struct xpu_base_addr_info g_xpu_base_addr_array[] = {
	{
		XPU_TYPE_AOSS_MPU,
		XPU_ADDR_TYPE(AOSS_CNOC_MPU_XPU3_GCR0),
		"AOSS_MPU",
	},
	{
		XPU_TYPE_DC_NOC_NON_BROADCAST_MPU,
		XPU_ADDR_TYPE(DC_NOC_QHS_NON_BROADCAST_MPU_XPU3_GCR0),
		"DC_NOC_NON_BROADCAST_MPU",
	},
	{
		XPU_TYPE_ANOC1_MPU,
		XPU_ADDR_TYPE(SNOC_AGGRE1_MS_MPU_XPU3_GCR0),
		"ANOC1_MPU",
	},
	{
		XPU_TYPE_ANOC2_MPU,
		XPU_ADDR_TYPE(SNOC_AGGRE2_MS_MPU_XPU3_GCR0),
		"ANOC2_MPU",
	},
	{
		XPU_TYPE_AOP_MS_MPU,
		XPU_ADDR_TYPE(AOP_MPU_XPU3_GCR0),
		"AOP_MS_MPU",
	},
	{
		XPU_TYPE_BAM_BLSP1_DMA,
		XPU_ADDR_TYPE(QUPV3_0_XPU3_GCR0),
		"BAM_BLSP1_DMA",
	},
	{
		XPU_TYPE_BAM_BLSP2_DMA,
		XPU_ADDR_TYPE(QUPV3_1_XPU3_GCR0),
		"BAM_BLSP2_DMA",
	},
	{
		XPU_TYPE_BAM_BLSP3_DMA,
		XPU_ADDR_TYPE(QUPV3_2_XPU3_GCR0),
		"BAM_BLSP3_DMA",
	},
	{
		XPU_TYPE_QUP_AXI,
		XPU_ADDR_TYPE(QUPV3_3_AXI_XPU3_GCR0),
		"QUPV3_AXI",
	},
	{
		XPU_TYPE_BIMC_MPU0,
		XPU_ADDR_TYPE(LLCC0_LLCC_MPU_XPU3_GCR0),
		"BIMC_MPU0",
	},
	{
		XPU_TYPE_BIMC_MPU1,
		XPU_ADDR_TYPE(LLCC1_LLCC_MPU_XPU3_GCR0),
		"BIMC_MPU1",
	},
	{
		XPU_TYPE_BIMC_MPU2,
		XPU_ADDR_TYPE(LLCC2_LLCC_MPU_XPU3_GCR0),
		"BIMC_MPU2",
	},
	{
		XPU_TYPE_BIMC_MPU3,
		XPU_ADDR_TYPE(LLCC3_LLCC_MPU_XPU3_GCR0),
		"BIMC_MPU3",
	},
	{
		XPU_TYPE_BIMC_MPU4,
		XPU_ADDR_TYPE(LLCC4_LLCC_MPU_XPU3_GCR0),
		"BIMC_MPU4",
	},
	{
		XPU_TYPE_BIMC_MPU5,
		XPU_ADDR_TYPE(LLCC5_LLCC_MPU_XPU3_GCR0),
		"BIMC_MPU5",
	},
	{
		XPU_TYPE_BOOT_IMEM_SS_MPU,
		XPU_ADDR_TYPE(CNOC_BOOT_IMEM_SS_MPU_XPU3_GCR0),
		"BOOT_IMEM_SS_MPU",
	},
	{
		XPU_TYPE_BOOT_ROM,
		XPU_ADDR_TYPE(BOOT_ROM_XPU3_GCR0),
		"BOOT_ROM",
	},
	{
		XPU_TYPE_CNOC_AOSS_MPU,
		XPU_ADDR_TYPE(CNOC_AOSS_MPU_XPU3_GCR0),
		"CNOC_AOSS_MPU",
	},
	{
		XPU_TYPE_CNOC_SNOC_MPU,
		XPU_ADDR_TYPE(CNOC_SS_MPU_XPU3_GCR0),
		"CNOC_SNOC_MPU",
	},
	{
		XPU_TYPE_CNOC_SNOC_MS_MPU,
		XPU_ADDR_TYPE(CNOC_GEMNOC_MPU_XPU3_GCR0),
		"CNOC_SNOC_MS_MPU",
	},
	{
		XPU_TYPE_CRYPTO0_BAM,
		XPU_ADDR_TYPE(CRYPTO0_CRYPTO_BAM_XPU3_GCR0),
		"CRYPTO0_BAM",
	},
	{
		XPU_TYPE_CRYPTO1_BAM,
		XPU_ADDR_TYPE(CRYPTO1_CRYPTO_BAM_XPU3_GCR0),
		"CRYPTO1_BAM",
	},
	{
		XPU_TYPE_CRYPTO0_CRYPTO_KM_APU,
		XPU_ADDR_TYPE(CRYPTO0_CRYPTO_KM_XPU3_GCR0),
		"CRYPTO0_CRYPTO_KM_APU",
	},
	{
		XPU_TYPE_CRYPTO1_CRYPTO_KM_APU,
		XPU_ADDR_TYPE(CRYPTO1_CRYPTO_KM_XPU3_GCR0),
		"CRYPTO1_CRYPTO_KM_APU",
	},
	{
		XPU_TYPE_DC_NOC_SHRM_MPU,
		XPU_ADDR_TYPE(DC_NOC_QHM_SHRM_MPU_XPU3_GCR0),
		"DC_NOC_QHM_SHRM_MPU",
	},
	{
		XPU_TYPE_DCC,
		XPU_ADDR_TYPE(QDSS_DCC_DCC_XPU3_GCR0),
		"DCC",
	},
	{
		XPU_TYPE_ETH_MS_MPU,
		XPU_ADDR_TYPE(AGGRE_NOC_SAIL_ETH_MS_MPU_XPU3_GCR0),
		"ETH_MPU",
	},
	{
		XPU_TYPE_GCC_RPU,
		XPU_ADDR_TYPE(GCC_RPU_XPU3_GCR0),
		"GCC_RPU",
	},
	{
		XPU_TYPE_GIC_MS_MPU,
		XPU_ADDR_TYPE(SNOC_GIC_MS_MPU_XPU3_GCR0),
		"GIC_MS_MPU",
	},
	{
		XPU_TYPE_APSS_GIC_WRAPPER_MS_MPU,
		XPU_ADDR_TYPE(APSS_GIC_NOC_WRAPPERGIC_NOC_EPSS_MS_MPU_XPU3_GCR0),
		"APSS_GIC_MS_MPU",
	},
	{
		XPU_TYPE_HWKM_CFG_KM_APU,
		XPU_ADDR_TYPE(HWKM_MASTER_CFG_KM_XPU3_GCR0),
		"HWKM_CFG_KM_APU",
	},
	{
		XPU_TYPE_IMEM_APU,
		XPU_ADDR_TYPE(OCIMEM_APU_XPU3_GCR0),
		"IMEM_APU",
	},
	{
		XPU_TYPE_IMEM_MPU,
		XPU_ADDR_TYPE(OCIMEM_MPU_XPU3_GCR0),
		"IMEM_MPU",
	},
	{
		XPU_TYPE_IPA_0_GSI_TOP,
		XPU_ADDR_TYPE(GSI_TOP_XPU3_GCR0),
		"IPA_0_GSI_TOP",
	},
	{
		XPU_TYPE_IPC_MPU,
		XPU_ADDR_TYPE(IPC_SOC_XPU3_GCR0),
		"IPC_MPU",
	},
	{
		XPU_TYPE_LLCC_BROADCAST_MPU,
		XPU_ADDR_TYPE(LLC_BROADCAST_LLCC_MPU_XPU3_GCR0),
		"LLCC_BROADCAST_MPU",
	},
	{
		XPU_TYPE_LPASS_CFG_MPU,
		XPU_ADDR_TYPE(XPU_CFG_LPASS_XPU3_GCR0),
		"LPASS_CFG",
	},
	{
		XPU_TYPE_LPASS_RXTX_MPU,
		XPU_ADDR_TYPE(LPASS_RXTX_XPU3_GCR0),
		"LPASS_RXTX",
	},
	{
		XPU_TYPE_LPASS_SSC_Q6_MPU,
		XPU_ADDR_TYPE(LPASS_Q6_MPU_XPU3_GCR0),
		"LPASS_Q6",
	},
	{
		XPU_TYPE_LPASS_VA_MPU,
		XPU_ADDR_TYPE(LPASS_VA_XPU3_GCR0),
		"LPASS_VA",
	},
	{
		XPU_TYPE_LPASS_WSA_MPU,
		XPU_ADDR_TYPE(LPASS_WSA_XPU3_GCR0),
		"LPASS_WSA",
	},
	{
		XPU_TYPE_LPASS_XPU_AUD,
		XPU_ADDR_TYPE(LPASS_AUD_XPU3_GCR0),
		"LPASS_AUD",
	},
	{
		XPU_TYPE_LPASS_XPU_AUD_SB,
		XPU_ADDR_TYPE(LPASS_AUD_SB_XPU3_GCR0),
		"LPASS_AUD_SB",
	},
	{
		XPU_TYPE_LPASS_WSA_2CH_MPU,
		XPU_ADDR_TYPE(LPASS_WSA_2CH_XPU3_GCR0),
		"LPASS_WSA_2CH",
	},
	{
		XPU_TYPE_LPASS_DEBUG_MPU,
		XPU_ADDR_TYPE(LPASS_DEBUG_MPU_XPU3_GCR0),
		"LPASS_DEBUG_MPU",
	},
	{
		XPU_TYPE_MDSS0,
		XPU_ADDR_TYPE(MDSS_0_MDSS_XPU_XPU3_GCR0),
		"MDSS0_XPU",
	},
	{
		XPU_TYPE_MDSS1,
		XPU_ADDR_TYPE(MDSS_1_MDSS_XPU_XPU3_GCR0),
		"MDSS1_XPU",
	},
	{
		XPU_TYPE_PKE_APU,
		XPU_ADDR_TYPE(PKE_WRAPPER_XPU3_GCR0),
		"PKE_APU",
	},
	{
		XPU_TYPE_PMIC_ARB,
		XPU_ADDR_TYPE(PMIC_ARB_XPU3_GCR0),
		"PMIC_ARB",
	},
	{
		XPU_TYPE_QM_MPU_CFG,
		XPU_ADDR_TYPE(QM_MPU_CFG_XPU3_GCR0),
		"QM_MPU_CFG",
	},
	{
		XPU_TYPE_RAMBLUR_PIMEM_APU,
		XPU_ADDR_TYPE(RAMBLUR_PIMEM_APU_XPU3_GCR0),
		"RAMBLUR_PIMEM_APU",
	},
	{
		XPU_TYPE_RAMBLUR_PIMEM_MPU,
		XPU_ADDR_TYPE(RAMBLUR_PIMEM_MPU_XPU3_GCR0),
		"RAMBLUR_PIMEM_MPU",
	},
	{
		XPU_TYPE_R52_MS_MPU,
		XPU_ADDR_TYPE(AGGRE_NOC_SAIL_R52_MS_MPU_XPU3_GCR0),
		"R52_MS_MPU",
	},
	{
		XPU_TYPE_SDC1_SDCC_ICE,
		XPU_ADDR_TYPE(PERIPH_SS_SDC1_SDCC_ICE_XPU3_GCR0),
		"PERIPH_SS",
	},
	{
		XPU_TYPE_SDC1_SDCC_ICE_KM_APU,
		XPU_ADDR_TYPE(PERIPH_SS_SDC1_SDCC_ICE_KM_XPU3_GCR0),
		"PERIPH_SS_KM",
	},
	{
		XPU_TYPE_SEC_CTRL_APU,
		XPU_ADDR_TYPE(SEC_CTRL_APU_XPU3_GCR0),
		"SEC_CTRL_APU",
	},
	{
		XPU_TYPE_SPDM_APU,
		XPU_ADDR_TYPE(QDSS_DCC_DCC_XPU3_GCR0),
		"SPDM_APU",
	},
	{
		XPU_TYPE_LPASS_Q6SS_MPU,
		XPU_ADDR_TYPE(LPASS_Q6_MPU_XPU3_GCR0),
		"LPASS_Q6_MPU",
	},
	{
		XPU_TYPE_TCSR_MUTEX,
		XPU_ADDR_TYPE(TCSR_MUTEX_XPU3_GCR0),
		"TCSR_MUTEX",
	},
	{
		XPU_TYPE_TCSR_REGS,
		XPU_ADDR_TYPE(TCSR_REGS_XPU3_GCR0),
		"TCSR_REGS",
	},
	{
		XPU_TYPE_TITAN_SS_APU1,
		XPU_ADDR_TYPE(TITAN_A_XPU3_1_XPU3_GCR0),
		"TITAN_SS_APU1",
	},
	{
		XPU_TYPE_TITAN_SS_APU2,
		XPU_ADDR_TYPE(TITAN_A_XPU3_2_XPU3_GCR0),
		"TITAN_SS_APU2",
	},
	{
		XPU_TYPE_TLMM,
		XPU_ADDR_TYPE(TLMM_XPU_XPU3_GCR0),
		"TLMM_XPU",
	},
	{
		XPU_TYPE_TSCSS_MPU,
		XPU_ADDR_TYPE(TSCSS_MPU_XPU3_GCR0),
		"TSCSS_MPU",
	},
	{
		XPU_TYPE_UFS_ICE,
		XPU_ADDR_TYPE(UFS_CARD_ICE_XPU3_GCR0),
		"UFS_CARD_ICE_KM_APU",
	},
	{
		XPU_TYPE_UFS_CARD_ICE_KM_APU,
		XPU_ADDR_TYPE(UFS_CARD_ICE_KM_XPU3_GCR0),
		"UFS_CARD_ICE_KM_APU",
	},
	{
		XPU_TYPE_UFS_G4_ICE,
		XPU_ADDR_TYPE(UFS_MEM_ICE_XPU3_GCR0),
		"UFS_ICE",
	},
	{
		XPU_TYPE_UFS_MEM_ICE_KM_APU,
		XPU_ADDR_TYPE(UFS_MEM_ICE_KM_XPU3_GCR0),
		"UFS_MEM_ICE_KM_APU",
	},
};

uint32_t g_xpu_base_addr_array_count = ARRAY_SIZE(g_xpu_base_addr_array);

void xpu_configure_tz(void)
{
	mmio_write_32(HWIO_IPA_0_GSI_TOP_XPU3_GCR0_ADDR + 0x8, 0x10f);
}
