/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <stdbool.h>

#include <lib/utils_def.h>
#include <vmidmt.h>
#include <vmidmt_internal.h>

/* Configuration/options for each VMIDMT. */
const struct vmidmt_cfg g_vmidmt_cfg[] = {
	{ HAL_VMIDMT_IPA, VMIDMT_ERR_OPT, NULL, 0, 1 },
	/* Rennell.QUPV3 0 VMIDMT SMR 48 SSD6 SID6 MA48 SP48 36 */
	{ HAL_VMIDMT_QUPV3_0, VMIDMT_ERR_OPT, NULL, 0, 1 },
	/* Rennell.QUPV3 1 VMIDMT SMR 48 SSD6 SID6 MA48 SP48 36 */
	{ HAL_VMIDMT_QUPV3_1, VMIDMT_ERR_OPT, NULL, 0, 1 },
};

const uint32_t g_vmidmt_cfg_count = ARRAY_SIZE(g_vmidmt_cfg);

/* Mapping from master indices to VMIDs. */
const struct vmidmt_map g_vmid_map[] = {
	{ HAL_VMIDMT_IPA,
	  0,
	  { 0 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  1,
	  { 1 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  2,
	  { 2 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  3,
	  { 3 },
	  1,
	  ACC_VMID_IPA_PERIPH_1,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  4,
	  { 4 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  5,
	  { 5 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  6,
	  { 6 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  7,
	  { 7 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  8,
	  { 8 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  9,
	  { 9 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  10,
	  { 10 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  11,
	  { 11 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  12,
	  { 12 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  13,
	  { 13 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  14,
	  { 14 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  15,
	  { 15 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  16,
	  { 16 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  17,
	  { 17 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  18,
	  { 18 },
	  1,
	  ACC_VMID_IPA_PERIPH_1,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  19,
	  { 19 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  20,
	  { 20 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  21,
	  { 21 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  22,
	  { 22 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  32,
	  { 32 },
	  1,
	  ACC_VMID_IPA_GP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  33,
	  { 33 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  34,
	  { 34 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  40,
	  { 40 },
	  1,
	  ACC_VMID_IPA_FW,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  41,
	  { 41 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_IPA,
	  48,
	  { 48 },
	  1,
	  ACC_VMID_NOACCESS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	/* 3_0 */
	{ HAL_VMIDMT_QUPV3_0,
	  0,
	  { 0 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  1,
	  { 1 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  2,
	  { 2 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  3,
	  { 3 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  4,
	  { 4 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  5,
	  { 5 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  6,
	  { 6 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  7,
	  { 7 },
	  1,
	  ACC_VMID_LPASS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  8,
	  { 8 },
	  1,
	  ACC_VMID_LPASS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  11,
	  { 11 },
	  1,
	  ACC_VMID_MSS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  16,
	  { 16 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  17,
	  { 17 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  18,
	  { 18 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  19,
	  { 19 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  20,
	  { 20 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  21,
	  { 21 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  22,
	  { 22 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  23,
	  { 23 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  32,
	  { 32 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  33,
	  { 33 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  34,
	  { 34 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  35,
	  { 35 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  36,
	  { 36 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  37,
	  { 37 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_0,
	  38,
	  { 38 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	/* 3_1 */
	{ HAL_VMIDMT_QUPV3_1,
	  0,
	  { 0 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  1,
	  { 1 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  2,
	  { 2 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  3,
	  { 3 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  4,
	  { 4 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  5,
	  { 5 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  6,
	  { 6 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  7,
	  { 7 },
	  1,
	  ACC_VMID_LPASS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  8,
	  { 8 },
	  1,
	  ACC_VMID_LPASS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  11,
	  { 11 },
	  1,
	  ACC_VMID_MSS,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  16,
	  { 16 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  17,
	  { 17 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  18,
	  { 18 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  19,
	  { 19 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  20,
	  { 20 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  21,
	  { 21 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  22,
	  { 22 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  23,
	  { 23 },
	  1,
	  ACC_VMID_AP,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  32,
	  { 32 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  33,
	  { 33 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  34,
	  { 34 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  35,
	  { 35 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  36,
	  { 36 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  37,
	  { 37 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
	{ HAL_VMIDMT_QUPV3_1,
	  38,
	  { 38 },
	  1,
	  ACC_VMID_AP_GSI,
	  1,
	  ACC_VMIDMT_MEMTYPE_DEFAULT },
};

const uint32_t g_vmid_map_count = ARRAY_SIZE(g_vmid_map);

#define IPA_0_IPA_VMIDMT_SCR0_ADDR (0x01E30000)
#define QUPV3_0_VMIDMT_SCR0_ADDR (0x009C6000)
#define QUPV3_1_VMIDMT_SCR0_ADDR (0x00AC6000)
#define SSC_QUPV3_VMIDMT_SCR0_ADDR (0x037C6000)

struct hal_vmidmt_port_map g_vmidmt_info_cfg[] = {
	{ HAL_VMIDMT_IPA,
	  { IPA_0_IPA_VMIDMT_SCR0_ADDR, { 40, 0, 0, 0, 0, false } } },
	{ HAL_VMIDMT_QUPV3_0,
	  { QUPV3_0_VMIDMT_SCR0_ADDR, { 48, 0, 0, 0, 0, false } } },
	{ HAL_VMIDMT_QUPV3_1,
	  { QUPV3_1_VMIDMT_SCR0_ADDR, { 48, 0, 0, 0, 0, false } } },
};

const uint8_t g_vmidmt_info_cfg_count = ARRAY_SIZE(g_vmidmt_info_cfg);

/*
 * Mapping of VMIDMT position in VMIDMT Error interrupt status register
 * to corresponding HAL VMIDMT index
 */
struct vmidmt_err_pos_to_hal_map vmidmt_err_pos_to_hal_map
	[ACC_VMIDMT_ERR_INT_STATUS_REG_NUM][ACC_VMIDMT_ERR_NUM_PER_REG] = {
		{
			{ 0, HAL_VMIDMT_CRYPTO0_BAM },
			{ 1, HAL_VMIDMT_AOP },
			{ 2, HAL_VMIDMT_QUPV3_0 },
			{ 3, HAL_VMIDMT_SSC_SDC },
			{ 4, HAL_VMIDMT_QUPV3_1 },
			{ 5, HAL_VMIDMT_QUPV3_2 },
			{ 6, HAL_VMIDMT_SSC_QUPV3 },
			{ 7, HAL_VMIDMT_LPASS_RXTX }, /* lpass_0_vmidmt_girpt */
			{ 8, HAL_VMIDMT_LPASS_VA }, /* lpass_1_vmidmt_girpt */
			{ 9, HAL_VMIDMT_IPA },
			{ 10, HAL_VMIDMT_QDSS_VMIDETR },
			{ 11, HAL_VMIDMT_QDSS_VMIDDAP },
			{ 12, HAL_VMIDMT_COUNT }, /* spdm_vmidmt_girpt */
			{ 13, HAL_VMIDMT_QSPI }, /* qspi_vmidmt_girpt */
			{ 14, HAL_VMIDMT_LPASS_WSA }, /* lpass_2_vmidmt_girpt */
			{ 15, HAL_VMIDMT_COUNT }, /* reserved */
			{ 16, HAL_VMIDMT_COUNT }, /* reserved */
			{ 17, HAL_VMIDMT_COUNT }, /* reserved */
		},
	};
