/*
 * Copyright (c) 2026, Qualcomm Technologies, Inc. and/or its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef VMIDMT_TARGET_HWIO_H
#define VMIDMT_TARGET_HWIO_H

#include <kodiak_def.h>

#define TCSR_TCSR_REGS_REG_BASE (QTI_CORE_TOP_CSR_BASE + 0x000c0000)
#define TCSR_TCSR_REGS_REG_BASE_SIZE 0x30000
#define TCSR_TCSR_REGS_REG_BASE_USED 0x2f010

#define HWIO_TCSR_VMIDMT_CLIENT_NON_SEC_IRQ_STATUS_REG_0_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x2010)
#define HWIO_TCSR_VMIDMT_CLIENT_NON_SEC_IRQ_STATUS_REG_0_RMSK 0x3ffff

#define HWIO_TCSR_VMIDMT_CLIENT_NON_SEC_IRQ_ENABLE_0_REG_0_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x2050)
#define HWIO_TCSR_VMIDMT_CLIENT_NON_SEC_IRQ_ENABLE_0_REG_0_RMSK 0x3ffff

#define HWIO_TCSR_VMIDMT_CFG_NON_SEC_IRQ_STATUS_REG_0_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x3000)
#define HWIO_TCSR_VMIDMT_CFG_NON_SEC_IRQ_STATUS_REG_0_RMSK 0x3ffff

#define HWIO_TCSR_VMIDMT_CFG_NON_SEC_IRQ_ENABLE_0_REG_0_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x3040)
#define HWIO_TCSR_VMIDMT_CFG_NON_SEC_IRQ_ENABLE_0_REG_0_RMSK 0x3ffff

#define HWIO_TCSR_VMIDMT_CLIENT_SEC_IRQ_STATUS_REG_0_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x4010)
#define HWIO_TCSR_VMIDMT_CLIENT_SEC_IRQ_STATUS_REG_0_RMSK 0x3ffff

#define HWIO_TCSR_VMIDMT_CLIENT_SEC_IRQ_ENABLE_0_REG_0_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x4050)
#define HWIO_TCSR_VMIDMT_CLIENT_SEC_IRQ_ENABLE_0_REG_0_RMSK 0x3ffff

#define HWIO_TCSR_VMIDMT_CFG_SEC_IRQ_STATUS_REG_0_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x5000)
#define HWIO_TCSR_VMIDMT_CFG_SEC_IRQ_STATUS_REG_0_RMSK 0x3ffff

#define HWIO_TCSR_VMIDMT_CFG_SEC_IRQ_ENABLE_0_REG_0_ADDR \
	(TCSR_TCSR_REGS_REG_BASE + 0x5040)
#define HWIO_TCSR_VMIDMT_CFG_SEC_IRQ_ENABLE_0_REG_0_RMSK 0x3ffff

#ifndef HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_ADDR
#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_ADDR \
	HWIO_TCSR_VMIDMT_CLIENT_SEC_IRQ_STATUS_REG_0_ADDR
#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_RMSK \
	HWIO_TCSR_VMIDMT_CLIENT_SEC_IRQ_STATUS_REG_0_RMSK
#endif

#ifndef HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_ADDR
#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_ADDR \
	HWIO_TCSR_VMIDMT_CLIENT_NON_SEC_IRQ_STATUS_REG_0_ADDR
#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_RMSK \
	HWIO_TCSR_VMIDMT_CLIENT_NON_SEC_IRQ_STATUS_REG_0_RMSK
#endif

#ifndef HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_ADDR
#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_ADDR \
	HWIO_TCSR_VMIDMT_CFG_SEC_IRQ_STATUS_REG_0_ADDR
#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_RMSK \
	HWIO_TCSR_VMIDMT_CFG_SEC_IRQ_STATUS_REG_0_RMSK
#endif

#ifndef HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_ADDR
#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_ADDR \
	HWIO_TCSR_VMIDMT_CFG_NON_SEC_IRQ_STATUS_REG_0_ADDR
#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_RMSK \
	HWIO_TCSR_VMIDMT_CFG_NON_SEC_IRQ_STATUS_REG_0_RMSK
#endif

#define HWIO_TCSR_SS_VMIDMT_CLIENT_SEC_INTR_ENABLE_ADDR \
	HWIO_TCSR_VMIDMT_CLIENT_SEC_IRQ_ENABLE_0_REG_0_ADDR

#define HWIO_TCSR_SS_VMIDMT_CLIENT_NON_SEC_INTR_ENABLE_ADDR \
	HWIO_TCSR_VMIDMT_CLIENT_NON_SEC_IRQ_ENABLE_0_REG_0_ADDR

#define HWIO_TCSR_SS_VMIDMT_CFG_SEC_INTR_ENABLE_ADDR \
	HWIO_TCSR_VMIDMT_CFG_SEC_IRQ_ENABLE_0_REG_0_ADDR

#define HWIO_TCSR_SS_VMIDMT_CFG_NON_SEC_INTR_ENABLE_ADDR \
	HWIO_TCSR_VMIDMT_CFG_NON_SEC_IRQ_ENABLE_0_REG_0_ADDR

#endif /* VMIDMT_TARGET_HWIO_H */
